# any values that should be overridden from what's in weblate can be added here.
# this can also be used for new strings.
# **Do not add player names to this file!
# ex: "無効": "Test"

OVERRIDE = {
    "このマップは モンスターから逃げられません。": "You can't run from monsters on this map.",
    "　　　～モンスター討伐隊隊員からの依頼～": "         Monster Strike Force Request",
    "神代過ぎ～　春の桜よ　無為に咲く～": "Past ages divine, the spring blossoms bloom, waiting idly by...",
    "プンスコのテーブル＆ティーセット": "Punsuko's Table & Tea Set",
    "扉は　かたく　閉ざされている。": "The door is tightly closed.",
    "闇に唄う氷にまぎれし聖なる者": "Frozen Sacred Singer",
    "ラダ・ガートたちに連絡を取る": "Contact Lada Gart's Group",
    "イア・タア　シンパッ・ケウ": "E-yis, aneu dish cubrey",
    "ドラゴンクエストＸショップ": "Dragon Quest X Shop",
    "『ついてクンをひっこめる』": "\"Remove Pet\"",
    "『おうちでついてクン設定』": "\"House Pet Settings\"",
    "清き風吹き　草木は芽吹く～": "Pure winds blown and trees grown, budding green as the breeze is thrown",
    "未来への扉とまどろみの少女": "The Door to the Future & the Slumbering Girl",
    "5000年の旅路 遥かなる故郷へ": "5000 Year Journey to a Faraway Hometown",
    "せんれきに　登録された！": "was registered in your Records!",
    "転生フィーバーおまじない": "Rarified Fever Charm",
    "ショップポイントをもらう": "Receive Shop Points",
    "ただの　しかばねのようだ": "It's just a corpse",
    "中断して天星郷に帰還する": "Suspend and Return to the Firmament",
    "『マイタウンへの出入り』": "\"Allowed to Visit\"",
    "なかまとの会話を振り返る": "Reflect on past conversations.",
    "いばらの巫女と滅びの神": "Thorny Maiden and the God of Destruction",
    "眠れる勇者と導きの盟友": "Sleeping Hero and Guiding Ally",
    "しぐさ書・きこえなーい": "Emote \"Can't Hear You\"",
    "カミルハムイにカンパイ": "cheers to Kamiruhamui",
    "イシュマウリオルゴール": "Ishmahri Music Box",
    "参加していきませんか？": "Do you want to go?",
    "ゴージャスケーキセット": "Gorgeous Cake Set",
    "プンスコのティーカップ": "Punsuko's Tea Cup",
    "第２回機神のトロフィー": "2nd Mech Trophy",
    "しぐさ書・この葉がくれ": "Emote \"Hide in Leaves\"",
    "モンスターバトルロード": "Monster Battle Road",
    "『カスタム衣装の登録』": "\"Register Outfit\"",
    "仮装メイク術の有効期間": "disguise duration",
    "バトルロードフィーバー": "Battle Road Fever",
    "誰に　声をかけますか？": "Speak with whom?",
    "氷にまぎれし聖なる者": "Frozen Sacred One",
    "目覚めし冒険者の広場": "Awakening Adventurer's Square",
    "次回の配布時期を聞く": "Ask About Next Distribution",
    "カムシカ・たづな無し": "Azlantelope without Reins",
    "アストルティア防衛軍": "Astoltia Defense Force",
    "カムシカ・たづなあり": "Azlantelope with Reins",
    "おたからさがしのすず": "Treasure Eye Land Bell",
    "るすばんエイドス４号": "Caretaker Eidos No. 4",
    "闇キーエンブレム洞窟": "Dark Key Emblem Cave",
    "闇キーエンブレムボス": "Dark Key Emblem Boss",
    "マザー・へレナの部屋": "Mother Helena's room",
    "銀ドラガイトロフィー": "Silver Dragon Trophy",
    "銅ドラガイトロフィー": "Bronze Dragon Trophy",
    "銀ドラキートロフィー": "Silver Dracky Trophy",
    "銅ドラキートロフィー": "Bronze Dracky Trophy",
    "嵐なき森に佇む獣の王": "Calm King of Beasts",
    "王様気分になれる玉座": "Throne to Be a King",
    "記念ふくびきマジック": "Commemorative Magic",
    "ビクトリーチップ・黄": "Yellow Victory Chip",
    "ビクトリーチップ・紫": "Purple Victory Chip",
    "ねこまどうぬいぐるみ": "Meowgician Plushie",
    "金ドラガイトロフィー": "Gold Dragon Trophy",
    "金ドラキートロフィー": "Gold Dracky Trophy",
    "静かな蒼穹のほほえみ": "Tranquil Azure Smile",
    "ビクトリーチップ・青": "Blue Victory Chip",
    "ビクトリーチップ・緑": "Green Victory Chip",
    "ケーキ神のぬいぐるみ": "Cake God Plushie",
    "『いまどんな？設定』": "Status Icon",
    "ハッピーバレンタイン": "Happy Valentine's Day",
    "ハッピーホワイトデー": "Happy White Day",
    "カブたちに連絡を取る": "Contact Kabu's Group",
    "アストルティアラリー": "Astoltia Rally",
    "マジカル★カーニバル": "Magical Carnival",
    "『ついてクンを選ぶ』": "\"Choose Pet\"",
    "レクスルクスの研究室": "Lexlux Laboratory",
    "Reツリーは白銀に消ゆ": "Tree's Disappearance Again",
    "GPトロフィーピンク銀": "Pink GP Silver Trophy",
    "GPトロフィーピンク銅": "Pink GP Bronze Trophy",
    "GPトロフィーピンク金": "Pink GP Gold Trophy",
    "GPトロフィーピンク鉄": "Pink GP Iron Trophy",
    "GPトロフィーアクア金": "GP Gold Trophy Aqua",
    "GPトロフィーアクア銀": "GP Silver Trophy Aqua",
    "GPトロフィーアクア銅": "GP Bronze Trophy Aqua",
    "GPトロフィーアクア鉄": "GP Steel Trophy Aqua",
    "闇に唄う白面の隠者": "Dark Singing Hermit",
    "目覚めし五つの種族": "Awakening of the Five Tribes",
    "いにしえの竜の伝承": "Lore of the Ancient Dragon",
    "素材タネ屋ムントン": "Material Seed Shop Munton",
    "封印危機対策委員会": "Sealing Crisis Committee",
    "偽りのエテーネの島": "False Ethene Island",
    "北の渡し守べニーズ": "North Ferryman Benize",
    "だいまどうのうでわ": "Great Mage Bracelets",
    "かたりべのてぶくろ": "Storyteller's Gloves",
    "水しぶき舞う海の精": "Splashing Sea Spirit",
    "よろず屋ドロッジェ": "General Shop Drogger",
    "ダーマ神官ネイシャ": "Abbey Priest Neisha",
    "きじゅつしのぼうし": "Illusionist's Hat",
    "はじめてのさいほう": "Starter Sewing",
    "宇宙船アルウェーン": "Spacecraft Alweyn",
    "水底にたゆたうもの": "Undersea Dwellers",
    "マスター・クレップ": "Guildmaster Krepp",
    "ようせいのあまざけ": "Fairy Sweet Sake",
    "マスター・アーリュ": "Guildmaster Aryu",
    "偽りのレンダーシア": "False Lendersia",
    "いっぱつのてぶくろ": "One Shot Gloves",
    "うぉークンカプセル": "War Pet Toy",
    "炎うず巻く聖なる鳥": "Fiery Holy Bird",
    "だいまどうのぼうし": "Great Mage Hat",
    "くろがねのはちがね": "Darksteel Headband",
    "とこしえのゆりかご": "Eternal Cradle",
    "シャークキングダム": "Shark Kingdom",
    "ふんさいのおおなた": "Heavy Hatchet",
    "せいどうのかなづち": "Bronze Hammer",
    "せかいじゅのしずく": "Yggdrasil Dew",
    "けんじゃのせいすい": "Sage's Elixir",
    "くらげドレスセット": "Jellyfish Dress Set",
    "竜将のよろいセット": "Dragon General Armor Set",
    "昔日のよろいセット": "Ancient Armor Set",
    "スノースターセット": "Snowstar Outfit",
    "バイカラーメッシュ": "Bicolor Mesh",
    "ブルートライデント": "Blue Trident",
    "わだつみのかんむり": "Sea God Crown",
    "バトエンファイター": "Batoen Fighter",
    "ふっかつのじゅもん": "Spell of Restoration",
    "仮装メイク術の効果": "disguise makeup effect",
    "サロン・フェリシア": "Salon Felicia",
    "キャット・バルバド": "Purrseidon",
    "アルカナ・セラピア": "Arcana Serapia",
    "果ての大地ゼニアス": "Zeniath",
    "みんなに声をかける": "Speak with everyone.",
    "蘇生時 早詠みの杖": "Faster Caster Savior",
    "武闘家ヤーン分身C": "Martial Artist Yarn Copy C",
    "神具解放の審問宮": "Sanctuary of Divine Relics",
    "ヴァース山林地帯": "Verse Mountain Forest Area",
    "武器防具屋ソロリ": "Weapon & Armor Shop Sorori",
    "セレドの民家庭具": "Celed House Decor (G)",
    "素材タネ屋コイズ": "Material Seed Shop Koiz",
    "素材タネ屋ピード": "Material Seed Shop Peid",
    "まじないしのくつ": "Fizzle-Proof Shoes",
    "装飾具屋ピッタン": "Decoration Shop Pittan",
    "真のエテーネの島": "True Ethene Island",
    "魔の波動を調べる": "Examine Demonic Waves",
    "怨霊の憑いた戦士": "Warrior With a Grudge",
    "転送係エグバート": "Transfer Agent Egbert",
    "素材屋ジョスリン": "Material Shop Joslyn",
    "モンスター討伐隊": "Monster Strike Force",
    "よろず屋ポロペン": "General Shop Poropen",
    "よろず屋ペピール": "General Shop Pepeelu",
    "素材屋ミルフィプ": "Material Shop Mirfpu",
    "よろず屋ピンドフ": "General Shop Pindoff",
    "よろず屋ペリトン": "General Shop Periton",
    "よろず屋パサンタ": "General Shop Pasanta",
    "ドワチャッカ大陸": "Dwachakka",
    "グランゼドーラ兵": "Gran Zedora Soldier",
    "エテーネ軍の兵士": "Ethene Army Soldier",
    "よろず屋ルキーノ": "General Shop Lukino",
    "よろず屋カトラズ": "General Shop Katraz",
    "レシピ屋アルキパ": "Recipe Shop Archipa",
    "よろず屋プロシオ": "General Shop Proshi",
    "ジア・クト念晶体": "Dia Kut telecrystal",
    "しっかりせんべい": "Firm Rice Cracker",
    "天かける七色の橋": "Rainbow Sky Bridge",
    "よろず屋スワーニ": "General Shop Swani",
    "参加受付クライブ": "Receptionist Clive",
    "ダーマ神官アデラ": "Abbey Priest Adela",
    "よろず屋ヤップイ": "General Shop Yapui",
    "よろず屋ポナック": "General Shop Ponak",
    "よろず屋リューロ": "General Shop Ryuro",
    "紺碧のピラー根本": "Azure Pillar Root",
    "かたりべのぼうし": "Storyteller's Hat",
    "きようさにくまん": "Deft Meat Buns",
    "ヨロイの幽霊さん": "Mr. Yoroi's ghost",
    "全滅時の復活場所": "resurrection spot",
    "よろず屋ガーディ": "General Shop Gadi",
    "オーグリード大陸": "Ogreed",
    "ひらめきのゆびわ": "Sorcerer's Stone",
    "さとりのかんむり": "Crown of Clarity",
    "ぬすっとのうでわ": "Robber's Bangles",
    "だいまどうのくつ": "Great Mage Shoes",
    "ヴェリナード王国": "Verinard Kingdom",
    "ガートラント兵士": "Gartlant Soldier",
    "ほっとするかばん": "Comforting Bag",
    "ようせいのおでん": "Fairy Hot Stick",
    "マドロック海賊団": "Madlock Pirates",
    "天翼のエンブレム": "Heavenly Emblem",
    "くさりのはちがね": "Chain Headgear",
    "真のレンダーシア": "True Lendersia",
    "ほしくずのつるぎ": "Stardust Sword",
    "やいばのはちがね": "Spiked Circlet",
    "よごれたほうたい": "Grubby Bandage",
    "わだつみのしずく": "Abyss Droplets",
    "いっぱつのよろい": "One Shot Armor",
    "いっぱつのつるぎ": "One Shot Sword",
    "ベルヴァインの森": "Belvain Forest",
    "ゾンビブラザーズ": "Zombie Brother",
    "﻿ステージ管理人": "Stage Manager",
    "まじんのかなづち": "Hela's Hammer",
    "くさりのあみごて": "Chain Bracers",
    "ときのすいしょう": "Chronocrystal",
    "しにがみのずきん": "Reaper's Hood",
    "輝ける生命の群生": "Swarm of Life",
    "預かり所ぺイジー": "Storage Peiji",
    "せいどうのつるぎ": "Bronze Sword",
    "はがねのかなづち": "Steel Hammer",
    "ましょうのおうぎ": "Devilish Fan",
    "ひっさつのおうぎ": "Critical Fan",
    "まどうしのぼうし": "Wizard's Hat",
    "ごきげんなぼうし": "Happy Hat",
    "いっぱつのぼうし": "One Shot Hat",
    "ドラゴンクエスト": "Dragon Quest",
    "パンプキンキッズ": "Pumpkin kids",
    "ぎょうじゃのこん": "Ascetic Rod",
    "くじゃくのおうぎ": "Peacock Fan",
    "ほうおうのおうぎ": "Phoenix Fan",
    "せいどうのかぶと": "Bronze Helm",
    "みかわしのぼうし": "Evasion Cap",
    "ひつじのてぶくろ": "Sheep Mitts",
    "くさりのあみぐつ": "Chain Boots",
    "まほうのせいすい": "Magic Water",
    "さざなみのしずく": "Rippledrops",
    "おうごんのかけら": "Gold Nuglet",
    "すずらんのゆかた": "Lily Yukata",
    "ショップポイント": "Shop Points",
    "いまどんな？設定": "Status Icon",
    "まわりにチャット": "Nearby Chat",
    "うさぎのおまもり": "Bunny Tail",
    "さすらいのぼうし": "Errant Hat",
    "天蓋付きのベッド": "Canopy Bed",
    "（だいじなもの）": " (Key Item)",
    "たいようのおうぎ": "Solar Fan",
    "はくあいのゆびわ": "Care Ring",
    "ようせいのひだね": "Lamplight",
    "イラッシャイマセ": "Welcome",
    "しんごんのじゅず": "Rosary",
    "なかまモンスター": "fellow monster",
    "メラゾ熱ワクチン": "Kafrizz Fever vaccine",
    "オルフェアリーズ": "Orphearies",
    "グレンドラゴニア": "Glendragonia",
    "ドルタムの念晶鏡": "Doltam's Telecrystal Mirror",
    "壁かけパッケージ": "Wall Hanging Package",
    "ドルボードレース": "Dolboard race",
    "ウェルカムハウス": "Welcome House",
    "『他の人の家へ』": "\"To Other House\"",
    "『だれでもＯＫ』": "\"Anyone is OK\"",
    "おしゃれカタログ": "Fashion Catalog",
    "トランプポイント": "Card Points",
    "フォルムチェンジ": "form change",
    "スライムくんたち": "Slime monsters",
    "カジノレイド祭り": "Casino Raid Festival",
    "家具＆庭具おきば": "furniture storage",
    "グレイナル叙事詩": "Epic of Greygnarl",
    "GPトロフィー黄銀": "Yellow GP Silver Trophy",
    "GPトロフィー黄銅": "Yellow GP Bronze Trophy",
    "GPトロフィー白銀": "White GP Silver Trophy",
    "GPトロフィー白銅": "White GP Bronze Trophy",
    "GPトロフィー黄金": "Yellow GP Gold Trophy",
    "GPトロフィー黄鉄": "Yellow GP Iron Trophy",
    "GPトロフィー白金": "White GP Gold Trophy",
    "GPトロフィー白鉄": "White GP Iron Trophy",
    "GPトロフィー紫金": "GP Gold Trophy Purple",
    "GPトロフィー紫銀": "GP Silver Trophy Purple",
    "GPトロフィー紫銅": "GP Bronze Trophy Purple",
    "GPトロフィー紫鉄": "GP Steel Trophy Purple",
    "GPトロフィー朱金": "GP Gold Trophy Red",
    "GPトロフィー朱銀": "GP Silver Trophy Red",
    "GPトロフィー朱鉄": "GP Steel Trophy Red",
    "ネジガラミの根": "Nejigarami root",
    "ゆりかごの末裔": "Descendants of the Cradle",
    "導きの水晶・黄": "Yellow Guidance Crystal",
    "導きの水晶・紫": "Purple Guidance Crystal",
    "導きの水晶・翠": "Green Guidance Crystal",
    "導きの水晶・黒": "Black Guidance Crystal",
    "辺境警備隊兵士": "Frontier Guard Soldier",
    "素材屋レヴェリ": "Material Shop Reverie",
    "素材屋ピノッピ": "Material Shop Pinoppi",
    "さくらのゆかた": "Cherry Blossom Yukata",
    "導きの水晶・蒼": "Blue Guidance Crystal",
    "天星の英雄たち": "Heroes of the Heavens",
    "転送係ガルニー": "Transfer Agent Garnie",
    "転送係ムタタプ": "Transfer Agent Muttap",
    "転送係フレデリ": "Transfer Agent Fredri",
    "転送係キャプン": "Transfer Agent Kyapun",
    "転送係プンペン": "Transfer Agent Punpen",
    "転送係コオモス": "Transfer Agent Coomos",
    "転送係ラアドワ": "Transfer Agent Radowa",
    "素材屋ミラベル": "Material Shop Mirabel",
    "素材屋ペピール": "Material Shop Pepeelu",
    "素材屋フレーツ": "Material Shop Fleets",
    "素材屋フウザム": "Material Shop Fuuzam",
    "導きの水晶・紅": "Red Guidance Crystal",
    "素材屋サビーラ": "Material Shop Sabira",
    "転送係ビエーロ": "Transfer Agent Viero",
    "素材屋セリーヌ": "Material Shop Celine",
    "素材屋ノーニャ": "Material Shop Nonya",
    "げんぶのかぶと": "Black Turtle Helmet",
    "くろがねのこて": "Darksteel Gauntlets",
    "しんこうのたね": "Seed of Therapeusis",
    "たまに２回攻撃": "Rarely Attack Twice",
    "ダーマのご神体": "Avatar of Alltrades",
    "よろず屋ゼクバ": "General Shop Zekuba",
    "演芸グランプリ": "Goofball Grand Prix",
    "プクランド大陸": "Pukuland",
    "古エテーネ王国": "Old Ethene Kingdom",
    "しんかのひせき": "Agate of Evolution",
    "こんぶ香る粘液": "Kelp-scented Mucus",
    "ベルトロの部下": "Bertro Subordinate",
    "スイの塔地下階": "Sui Tower Basement",
    "武器屋ルアンべ": "Weapon Shop Luambe",
    "紹介屋サパラン": "Refer Shop Saparan",
    "魔獣ヒュブロス": "Hubros",
    "武器屋クータス": "Weapon Shop Kootas",
    "タネ屋オダマキ": "Seed Shop Odamaki",
    "屋台系庭具１０": "Food Stall 10 (G)",
    "屋台系庭具１１": "Food Stall 11 (G)",
    "屋台系庭具１２": "Food Stall 12 (G)",
    "屋台系庭具１３": "Food Stall 13 (G)",
    "屋台系庭具１４": "Food Stall 14 (G)",
    "屋台系庭具１５": "Food Stall 15 (G)",
    "屋台系庭具１６": "Food Stall 16 (G)",
    "屋台系庭具１７": "Food Stall 17 (G)",
    "屋台系庭具１８": "Food Stall 18 (G)",
    "屋台系庭具１９": "Food Stall 19 (G)",
    "屋台系庭具２０": "Food Stall 20 (G)",
    "バケーロの子分": "Bakero's Henchman",
    "紹介屋メレーヌ": "Refer Shop Melene",
    "武器屋ブロルト": "Weapon Shop Brolt",
    "タネ屋ポッポル": "Seed Shop Poppol",
    "はがねのつるぎ": "Steel Broadsword",
    "せいどうのこて": "Bronze Gauntlets",
    "てつのすねあて": "Iron Shin Guards",
    "きようさのたね": "Seed of Deftness",
    "おうじょのあい": "Princess' Pledge",
    "ねがいのかがみ": "Mirror of Wishes",
    "転生モンスター": "rarified monster",
    "使徒キルパッポ": "Apostle Kilpappo",
    "バブスラジャム": "Bubble Slime Jam",
    "カミハルムイ北": "Kamiharmui North",
    "カミハルムイ南": "Kamiharmui South",
    "いなずまのやり": "Lightning Lance",
    "おにのかなぼう": "Marauder's Maul",
    "さとりのころも": "Robe of Clarity",
    "ぎんのはちがね": "Silver Headband",
    "すばやさのたね": "Seed of Agility",
    "まりょくのたね": "Seed of Sorcery",
    "しんせんたまご": "Free-Range Eggs",
    "さえずりのみつ": "Birdsong Nectar",
    "あまつゆのいと": "Celestial Skein",
    "なないろのまゆ": "Colorful Cocoon",
    "宿屋シルバーナ": "Innkeep Silvana",
    "防具屋ヴィーサ": "Armor Shop Visa",
    "もどりのつばさ": "Wing of Return",
    "ひきよせのすず": "Beckoning Bell",
    "ぎんのむねあて": "Silver Cuirass",
    "まもりのぼうし": "Safety Cap",
    "くすしのぼうし": "Apothecary Hat",
    "さすらいのこて": "Errant Bracers",
    "まどうしのくつ": "Wizard's Shoes",
    "ぬすっとのくつ": "Robber's Shoes",
    "かぜきりのはね": "Flurry Feather",
    "いっぱつのくつ": "One Shot Shoes",
    "かっこいい玉座": "Stylish Throne",
    "カブいてやがる": "unconventional",
    "おまとめぶくろ": "currencies bag",
    "料理屋パロンタ": "Server Paronta",
    "古ドワチャッカ": "Old Dwachakka",
    "はじゃのつるぎ": "Cautery Sword",
    "きせきのつるぎ": "Miracle Sword",
    "ぎんのかなづち": "Silver Hammer",
    "ちからのゆびわ": "Strength Ring",
    "てつのはちがね": "Iron Headband",
    "ぬすっとずきん": "Robber's Hood",
    "ぎんのこしだれ": "Silver Faulds",
    "みかわしのくつ": "Evasion Boots",
    "ふしぎなきのみ": "Seed of Magic",
    "せいじゃのはい": "Saint's Ashes",
    "自分をとうろく": "Register Self",
    "どうぐコマンド": "Items command",
    "料理屋パムック": "Server Pamuku",
    "取引商レリーン": "Trader Leleen",
    "ひかりのつるぎ": "Aurora Blade",
    "せいどうのやり": "Bronze Lance",
    "まどろみのこん": "Sleepy Stick",
    "てつのむねあて": "Iron Cuirass",
    "もみじのゆかた": "Maple Yukata",
    "はがねのかぶと": "Steel Helmet",
    "しんりのぼうし": "Faithful Hat",
    "さすらいのくつ": "Errant Shoes",
    "いのちのきのみ": "Seed of Life",
    "けんじゃのいし": "Sage's Stone",
    "台本を確認する": "Check Script",
    "フォース範囲化": "Fource Range",
    "ほのおのかぶと": "Flame Helmet",
    "荷馬車の作業員": "Wagon Worker",
    "ステテコパンツ": "Boxer Shorts",
    "マスタークラス": "Master Class",
    "こおりのやいば": "Icicle Dirk",
    "らいじんのやり": "Storm Spear",
    "いやしのぼうし": "Healing Hat",
    "てつのこしだれ": "Iron Faulds",
    "てつのうであて": "Iron Armguards",
    "せいれいのいと": "Spirit Yarn",
    "こうもりのはね": "Wing of Bat",
    "いかずちのたま": "Thunderball",
    "グルヤンラシュ": "Guryan Rush",
    "バトリンピック": "Battlympics",
    "ドクチョル先生": "Dr. Dokchul",
    "救助された侍女": "Relief Maid",
    "シスター・フプ": "Sister Fupu",
    "ほのおのつるぎ": "Fire Blade",
    "古オーグリード": "Old Ogreed",
    "えいゆうのやり": "Hero Spear",
    "うろこのかぶと": "Scale Helm",
    "ひつじのずきん": "Sheep Hood",
    "どうのこうせき": "Copper Ore",
    "ぎんのこうせき": "Silver Ore",
    "クエストリスト": "Quest List",
    "アントワネット": "Antoinette",
    "モバー＆イール": "Moe & Byle",
    "フウキのなかま": "SCC Member",
    "てつのかなぼう": "Iron Club",
    "にちりんのこん": "Solar Rod",
    "むぎわらぼうし": "Straw Hat",
    "おもいでのすず": "Evac-u-Bell",
    "へびのぬけがら": "Snakeskin",
    "スーパースター": "superstar",
    "アストルティア": "Astoltia",
    "ふしぎなぼうし": "Mad Cap",
    "きしんのまそう": "Poker",
    "ランプ錬金職人": "Lamp Alchemist",
    "サポートなかま": "support companion",
    "インスペクター": "inspector",
    "きせかえドール": "Dress-Up Doll",
    "経験値の古文書": "Experience Scroll",
    "バトエンマニア": "Batoenmania",
    "天狐アマツカゼ": "Amatsukaze",
    "ガタラアームズ": "Gatara Arms",
    "ナンナの水撃砲": "Nanna's Water Gun",
    "学園直通ホーム": "school direct platform",
    "スタンプリスト": "stamp list",
    "部の設備利用券": "Club Facility Ticket",
    "ランプ錬金部員": "Lamp Alchemy Club member",
    "ピュアジュエル": "Pure Jewel",
    "段位戦ポイント": "Rank Points",
    "コーディネイト": "outfit",
    "フレンドリスト": "friend list",
    "シールシーカー": "Sticker Seeker",
    "チャレンジャー": "challenger",
    "精神エネルギー": "psychic energy",
    "高機能錬金食品": "Efficient Alchemy Food",
    "アマラーク王国": "Amarak Kingdom",
    "ルーミリアの家": "Rumilia's House",
    "ダサいＴシャツ": "Tacky T-Shirt",
    "バトエンパック": "Batoen Pack",
    "華のウルフ道": "Path of the Flower Wolf",
    "混沌の魔術王": "Chaotic Sorceror King",
    "回復の泉庭具": "Healing Fountain (G)",
    "素材屋ミヅキ": "Material Shop Mizuki",
    "素材屋テラナ": "Material Shop Telana",
    "駅員マツノシ": "Attendant Matsunoshi",
    "素材屋ナディ": "Material Shop Nadie",
    "素材屋タブロ": "Material Shop Tablo",
    "素材屋ナナイ": "Material Shop Nanai",
    "素材屋アマネ": "Material Shop Amane",
    "素材屋ポーツ": "Material Shop Ports",
    "げんぶのくつ": "Black Turtle Shoes",
    "まもりのたね": "Seed of Resilience",
    "転送係タイズ": "Transfer Agent Taz",
    "転送係ダウラ": "Transfer Agent Dar",
    "転送係ツキヨ": "Transfer Agent Tsu",
    "儀式のころも": "ceremonial clothes",
    "武器屋モヌス": "Weapon Shop Monus",
    "回復の泉家具": "Healing Fountain",
    "タネ屋ゲラド": "Seed Shop Gerado",
    "エルトナ大陸": "Eltona",
    "やいばのこて": "Spiked Gauntlets",
    "まもりのくつ": "Safety Shoes",
    "くすしのくつ": "Apothecary Shoes",
    "ちからのたね": "Seed of Strength",
    "戦神の箱改２": "War God Box v2 2",
    "屋台系庭具９": "Food Stall 9 (G)",
    "街教会聖職者": "church clergyman",
    "防具屋スット": "Armor Shop Sutto",
    "タネ屋ツィネ": "Seed Shop Zinei",
    "その他の場所": "Other Locations",
    "てつのつるぎ": "Iron Broadsword",
    "さじんのやり": "Sandstorm Spear",
    "なげきのこん": "Rod of Mourning",
    "はがねのこて": "Steel Gauntlets",
    "まほうのこて": "Magic Gauntlets",
    "せいれいせき": "Enchanted Stone",
    "ヤマカミヌ王": "Yamakaminu King",
    "悦びの浮き島": "Floating Island",
    "ほのおのこて": "Flame Gauntlets",
    "商人ティサウ": "Merchant Tissau",
    "商人ルヤーナ": "Merchant Luyana",
    "タネ屋ニーノ": "Seed Shop Nino",
    "えんぶのこん": "Driller Pillar",
    "まよけのすず": "Banishing Bell",
    "しんりのくつ": "Faithful Shoes",
    "おもさのたね": "Seed of Weight",
    "ちょうのはね": "Butterfly Wing",
    "リプレイ報酬": "replay reward",
    "まものつかい": "Monster Master",
    "しらふじいろ": "white wisteris",
    "きこえなーい": "Can't Hear You",
    "町長の執務室": "Mayor's Office",
    "商人タサール": "Merchant Tasar",
    "使徒チャミミ": "Apostle Chamim",
    "使徒ホウガイ": "Apostle Hougai",
    "使徒ベニヒナ": "Apostle Beniha",
    "使徒セーケン": "Apostle Seiken",
    "ガケっぷち村": "Ruined Village",
    "やまざこの町": "Yamazako Town",
    "てんびんぼう": "Carrying Pole",
    "どくけしそう": "Antidotal Herb",
    "まんげつそう": "Moonwort Bulb",
    "薬剤設備・庭": "Medicinal Facility (G)",
    "そうびぶくろ": "equipment bag",
    "アマカムシカ": "Amazlantelope",
    "ジュレド王国": "Juled Kingdom",
    "店員ルワーレ": "Clerk Ruwarei",
    "神父エブラフ": "Father Ebluff",
    "オルパナ神官": "Priest Orpana",
    "どうのつるぎ": "Copper Sword",
    "おおかなづち": "Sledgehammer",
    "しゅらのこん": "Knockout Rod",
    "ものほしざお": "Laundry Pole",
    "ばんそうこう": "Bandage",
    "うろこのこて": "Scale Gloves",
    "うつくしそう": "Pretty Betsy",
    "かがやきそう": "Glimmergrass",
    "陶芸設備・庭": "Ceramics Facility (G)",
    "エレメント系": "Element-type",
    "聖者トゥバン": "Saint Thuban",
    "キャラの場所": "NPC Location",
    "難民キャンプ": "Refugee Camp",
    "店員テリップ": "Clerk Teripp",
    "海神のうろこ": "Abyss Scale",
    "オルクステラ": "Orchesterra",
    "はがねのやり": "Steel Lance",
    "やしゃのこん": "Slaying Rod",
    "ひつじのくつ": "Sheep Shoes",
    "あやかしそう": "Narspicious",
    "舞台に上がる": "Go on Stage",
    "グランゼニス": "Gran Zenith",
    "どうぐつかい": "Item Master",
    "うつしよの箱": "Worldly Box",
    "レース用の旗": "Racing Flag",
    "店員フリーダ": "Clerk Frida",
    "取引商タヴィ": "Trader Tavi",
    "取引商アンズ": "Trader Anzu",
    "聖なる織り機": "sacred loom",
    "カミハルムイ": "Kamiharmui",
    "らせつのこん": "Taming Rod",
    "ねこじゃらし": "Cat Teaser",
    "バルメシュケ": "Balmeschke",
    "アクラガレナ": "Akragarena",
    "レイダメテス": "Reidametes",
    "ラーディス王": "King Ladis",
    "アラハギーロ": "Al-Ahagiro",
    "ストロベリー": "strawberry",
    "デビルワイン": "devil wine",
    "コアブラック": "core black",
    "ベビーピンク": "light pink",
    "ライトグレー": "light gray",
    "フウキの仲間": "SCC Member",
    "まんねん菌床": "Old Fungus",
    "アビサルドン": "Abyssaldon",
    "プロッペくん": "Mr. Proppe",
    "小さなメダル": "Mini Medal",
    "時空のしるべ": "Leap Point",
    "ヘントタロウ": "Hentotarou",
    "レンダーシア": "Lendersia",
    "ナドラガンド": "Nadragand",
    "ドワチャッカ": "Dwachakka",
    "へびのおうぎ": "Cobra Fan",
    "ばしょうせん": "Frond Fan",
    "きんのゆびわ": "Gold Ring",
    "どくがのこな": "Coagulant",
    "よるのとばり": "Evencloth",
    "だいじなもの": "Key Items",
    "クリフゲーン": "Cliffgain",
    "プーポッパン": "Puupoppan",
    "サルファバル": "Sulphubal",
    "パチャティカ": "Pachatika",
    "ニブルヘイム": "Nibelheim",
    "メギストリス": "Megistris",
    "ピュアスノー": "pure snow",
    "チョコレート": "chocolate",
    "ダークプラム": "dark plum",
    "グレーブルー": "gray-blue",
    "ダークグレー": "dark gray",
    "ミストグレー": "mist gray",
    "シーグリーン": "sea green",
    "ピュアブルー": "pure blue",
    "ダークブルー": "dark blue",
    "ローズグレー": "rose gray",
    "スラマオイル": "Slime Oil",
    "ナイトグッド": "Nightgood",
    "ミス・ドール": "Miss Doll",
    "ベスカトーレ": "Vescatore",
    "ガートラント": "Gartlant",
    "いろいろ設定": "Settings",
    "てつのおうぎ": "Iron Fan",
    "きぬのぼうし": "Silk Hat",
    "てっこうせき": "Iron Ore",
    "みかわしそう": "Slipweed",
    "かぜのぼうし": "Wind Hat",
    "どうぐぶくろ": "item bag",
    "ファルシオン": "Falchion",
    "『まわりに』": "\"Nearby\"",
    "ジュリアンテ": "Juliante",
    "ヘルゲゴーグ": "Helgegog",
    "ヴィスタリア": "Vistaria",
    "ゾルトグリン": "Zoltgrin",
    "バイロゴーグ": "Biologog",
    "ファラザード": "Farazard",
    "バルディスタ": "Valdista",
    "メルサンディ": "Melsandy",
    "エピステーサ": "Epistesa",
    "ミッドナイト": "midnight",
    "アイスブルー": "ice blue",
    "スカイブルー": "sky blue",
    "どうぐかばん": "item bag",
    "キャロルギル": "Kyrolgyl",
    "バットエンド": "Bato-End",
    "フォーリオン": "Fourion",
    "『せんれき』": "Records",
    "つきのめぐみ": "Lunaria",
    "ラディスオー": "Ladisau",
    "リンジャーラ": "Linjara",
    "サンゴールド": "sungold",
    "ヴァルザード": "Valzard",
    "グレイツェル": "Gretzel",
    "シロウトさん": "amateur",
    "オーグリード": "Ogreed",
    "エンラージャ": "Enraja",
    "アスフェルド": "Asfeld",
    "バイオレット": "violet",
    "マクフォール": "McFaul",
    "コルシュール": "Corsur",
    "バサグランデ": "Bogan",
    "アクアマリン": "aqua",
    "と言われた。": "\"\"",
    "と頼まれた。": "\"\"",
    "エックスさん": "X",
    "サポート仲間": "support companion",
    "ツボ錬金職人": "Pot Alchemist",
    "ホンワカ羽毛": "Snuggly Feather",
    "キャンペーン": "campaign",
    "ディレクター": "director",
    "カラーリング": "coloring",
    "ベリナイスド": "Verinaice",
    "神官エステラ": "Priestess Estella",
    "インストール": "install",
    "さいほう職人": "Sewer",
    "武器鍛冶職人": "Weaponsmith",
    "防具鍛冶職人": "Armorsmith",
    "道具鍛冶職人": "Toolsmith",
    "ヴァニタトス": "Vanitatos",
    "ソウルメイト": "soulmate",
    "ガーディアン": "guardian",
    "四天の星巡り": "Four Heavenly Trials",
    "カブの烈火掌": "Kabu's Fiery Palm",
    "バトルロード": "Battle Road",
    "記者リーリナ": "Reporter Lilina",
    "ロトゼタシア": "Erdrea",
    "マイガーデン": "My Garden",
    "ランプ錬金部": "Lamp Alchemy Club",
    "ツボ錬金部員": "Pot Alchemy Club member",
    "道具鍛冶部員": "Toolsmithing Club member",
    "武器鍛冶部員": "Weaponsmithing Club member",
    "防具鍛冶部員": "Armorsmithing Club member",
    "部活強化週間": "Club Upgrade Week",
    "部活ポイント": "Club Points",
    "ユーシャさま": "Luminary",
    "仮装メイク術": "disguise makeup",
    "大富豪決定戦": "Tycoon Playoffs",
    "お知らせ広場": "Notification Square",
    "スライムくん": "Slime monster",
    "ダーマの神殿": "Alltrades Abbey",
    "カジノレイド": "Casino Raid",
    "ボロヌジウム": "Boronudium",
    "創世のピラー": "Pillar of Creation",
    "極致への道標": "Road to Perfection",
    "モンバーバラ": "Laissez Fayre",
    "レギルラッゾ": "Legirrazzo",
    "スコルパイド": "Scorpide",
    "ジェルザーク": "Gelzark",
    "花開きの聖祭": "Blooming Festival",
    "姉神封印神殿": "Goddess Seal Temple",
    "燈火の調査隊": "Ember Explorers",
    "ナブおじさん": "Mr. Nab",
    "奇跡のチカラ": "power of miracles",
    "バカンウグレ": "Bakanugure",
    "ごきげんよう": "how do you do",
    "パンパニーニ": "Panpanini",
    "プロジェクト": "project",
    "Pの　経験値": "EXP",
    "研究開発室": "Research and Development room",
    "転移の石碑": "Stele of Transportation",
    "返事がない": "There's no response",
    "ダーマの神": "Allmighty Alltrades",
    "守護の試練": "Trial of Protection",
    "家具屋ユク": "Furniture Shop Yuku",
    "帝国技術庁": "Empire Tech Agency",
    "一人前の証": "Mark of Maturity",
    "いやしそう": "Superior Medicine",
    "ダンダダ団": "Robbin' 'Ood Gang",
    "魔瘴の巫女": "maiden of miasma",
    "支援端末ノ": "Support Terminal",
    "隊商の仲間": "Merchant Caravan",
    "守護騎士団": "Guardian Knights",
    "不思議な駅": "Mystery Station",
    "おおばさみ": "Sizable Scissors",
    "ぎんのこて": "Silver Gauntlets",
    "世告げの姫": "Princess of Prophecy",
    "真偽の試練": "Trial of Truths",
    "闘志の試練": "Trial of Spirit",
    "某国の兵士": "Country Soldier",
    "回想の兵士": "Reflect Soldier",
    "ボルネア山": "Bornea Mountain",
    "プクリポ女": "Pukulipo woman",
    "丘の町地区": "Hill Town Area",
    "てつのこて": "Iron Gauntlets",
    "戦神の箱改": "War God Box v2",
    "げんませき": "Ethereal Stone",
    "まもの使い": "monster master",
    "流星の帝王": "Emperor Meteor",
    "手下の海賊": "Pirate Crewman",
    "闇の親衛隊": "Dark Bodyguard",
    "異形の大地": "Deformed Earth",
    "トロぺ神父": "Father Toropei",
    "商人パサル": "Merchant Pasal",
    "商人キュル": "Merchant Kyuru",
    "はねぼうし": "Feathered Cap",
    "わらぞうり": "Straw Sandals",
    "戦神の箱２": "War God Box 2",
    "皇女ウルタ": "Princess Ulta",
    "かっちゅう": "suit of armor",
    "破邪舟使い": "Sacred Sailor",
    "決戦用砲台": "Battle Cannon",
    "ローゼの剣": "Rosey's Sword",
    "商人タヴィ": "Merchant Tavi",
    "かいしん率": "critical rate",
    "闘いの広間": "Monstrous Pit",
    "ゼドラ集落": "Zedra Village",
    "どくけし茶": "antidotal tea",
    "プクリポ男": "Pukulipo man",
    "封印の聖壇": "Sealed Altar",
    "ウェナ諸島": "Wena Islands",
    "くさりがま": "Chain Sickle",
    "さとりそう": "Thinkincense",
    "うまのふん": "Horse Manure",
    "ゴブル砂漠": "Goble Desert",
    "ホルタ神父": "Father Holta",
    "破邪の秘技": "Sacred Skill",
    "破邪の紋章": "Sacred Crest",
    "店員タブレ": "Clerk Tabure",
    "ぼうそう率": "haywire rate",
    "はねおうぎ": "Feather Fan",
    "てつかぶと": "Iron Helmet",
    "ぶとうぎ２": "Strongsam 2",
    "どうぐ使い": "item master",
    "ドラゴン系": "Dragon-type",
    "説明を聞く": "Explanation",
    "説明をきく": "Explanation",
    "ジュレー島": "Jule Island",
    "あおりんご": "light green",
    "封印の聖灰": "Sealing Ash",
    "魔獣の寝床": "Beast's Bed",
    "仮面オレン": "Masked Oran",
    "店員ウラカ": "Clerk Uraka",
    "店員タウノ": "Clerk Tauno",
    "店員パフタ": "Clerk Pufta",
    "店員カンザ": "Clerk Kanza",
    "店員ユゴオ": "Clerk Yugoo",
    "店員マルル": "Clerk Marul",
    "聖なる織機": "sacred loom",
    "おおきづち": "Hammerhood",
    "受注中タブ": "Active Tab",
    "てつのやり": "Iron Lance",
    "かしのこん": "Oaken Pole",
    "みがきずな": "Glass Frit",
    "スライム系": "Slime-type",
    "ヤマカミヌ": "Yamakaminu",
    "ふかみどり": "dark green",
    "ろくしょう": "green rust",
    "きぞくねず": "noble gray",
    "ナスガルド": "Woebergard",
    "チュチピカ": "Chuchipika",
    "フブキ博士": "Dr. Fubuki",
    "店員グォン": "Clerk Guon",
    "店員ザール": "Clerk Zarr",
    "ろうがぼう": "Sadistick",
    "ワラキウス": "Warachius",
    "レクタ鉱石": "Lecta Ore",
    "ダイキリン": "Dai Kirin",
    "カルサドラ": "Calsadora",
    "キュララナ": "Kyurarana",
    "元ポツコン": "Ex-Junkey",
    "うすざくら": "pale pink",
    "ゆめみの箱": "Dream Box",
    "そうびひん": "equipment",
    "フローリス": "Fraulisse",
    "チャーチル": "Churchill",
    "マーガリン": "Margarine",
    "ラナダッタ": "Ranadatta",
    "マジュトツ": "Madjuttsu",
    "ザリガッパ": "Zarigappa",
    "シャドポン": "Shadowpon",
    "テストノノ": "Testonono",
    "ヒッピャぺ": "Hippyapei",
    "ゴノザマー": "Gonozamar",
    "店員ティア": "Clerk Tia",
    "マルコメス": "Malcomess",
    "グレイナル": "Greygnarl",
    "きつけそう": "Softwort",
    "ラッカラン": "Luckland",
    "プクランド": "Pukuland",
    "手に入れた": "received",
    "ベラストル": "Belastre",
    "ガズバラン": "Gazbalan",
    "レビュール": "Reviewle",
    "シナリディ": "Sinaridi",
    "やっつけた": "defeated",
    "イズヤノイ": "Izuyanoi",
    "ゾンガロン": "Zongalon",
    "ドミネウス": "Domineus",
    "ジャゴヌバ": "Jagonuba",
    "ネクロデア": "Necrodea",
    "ヤファギル": "Yaphagil",
    "ワラタロー": "Warataro",
    "ラニアッカ": "Raniakka",
    "アルケミア": "Alchemia",
    "ブルラトス": "Bulratos",
    "ラベンダー": "lavender",
    "アメジスト": "amethyst",
    "ビリジアン": "viridian",
    "シェルナー": "Shellner",
    "ホカホカな": "steaming",
    "ペルホネン": "Pelhonen",
    "ジェノール": "Gennault",
    "パピアット": "Papiatto",
    "キルパッポ": "Kilpappo",
    "チャケマエ": "Chakemae",
    "グリゼット": "Glisette",
    "クラリッサ": "Clarissa",
    "モチャチャ": "Mochacha",
    "メリーポコ": "Meripoko",
    "クックルン": "Cocoroon",
    "サフィール": "Sapphire",
    "アレサンド": "Alessand",
    "ブルーレス": "Blueleth",
    "バルバトゥ": "Barbatou",
    "ポスーリパ": "Posulipa",
    "キンクロス": "Kincross",
    "カーネリン": "Carnerin",
    "ボングワリ": "Bongwari",
    "チャッカバ": "Chakkaba",
    "パールポポ": "Palupopo",
    "ヘペラーナ": "Heperana",
    "プリュノー": "Pruneaux",
    "キムンカム": "Kimunkam",
    "スピンドル": "Spindle",
    "ドルワーム": "Dolworm",
    "マイコーデ": "Glamour",
    "ジア・クト": "Dia Kut",
    "プックレイ": "Pukklei",
    "ナシュロイ": "Nashroi",
    "アグシュナ": "Agushna",
    "ブロッゲン": "Broggen",
    "ラズバーン": "Razburn",
    "ゼルドラド": "Zeldrad",
    "チャーマン": "Charman",
    "エテーネル": "Ethenel",
    "レトリウス": "Retrius",
    "ルティアナ": "Lutiana",
    "アストロン": "Astoron",
    "マドロック": "Madlock",
    "ハルバルド": "Halbard",
    "ヴィゴレー": "Vigoray",
    "イプチャル": "Yppchal",
    "プクレット": "Pukulet",
    "ジャディン": "Jyadain",
    "キャラメル": "caramel",
    "エメラルド": "emerald",
    "カスタード": "custard",
    "ドクチョル": "Dokchul",
    "ディレーク": "Direkke",
    "パルペーラ": "Palpera",
    "プラティナ": "Platina",
    "プロフィテ": "Profite",
    "グリッチャ": "Gritcha",
    "ドロッジェ": "Drogger",
    "ペルトラン": "Pertran",
    "マルリーヌ": "Marlene",
    "パトローネ": "Patrone",
    "バーニジア": "Banijia",
    "クレッセル": "Kressel",
    "ポッピーナ": "Poppina",
    "プクッツォ": "Pukutso",
    "ベルトラム": "Bertram",
    "プリストン": "Priston",
    "パンドーラ": "Pandora",
    "ディアマン": "Diamond",
    "エムロード": "Emerald",
    "カルバンク": "Calbank",
    "アチュリン": "Achurin",
    "ルネドール": "Renedor",
    "リュシアン": "Lyucian",
    "エッカート": "Eckhart",
    "ロマンツェ": "Romanze",
    "ヨコジャン": "Yokojan",
    "ラデビュー": "Ladebyu",
    "パッキュレ": "Pakkure",
    "グラドマン": "Gladman",
    "クリスタル": "Crystal",
    "コロレッド": "Coroled",
    "ノレイジャ": "Noreija",
    "アクイラエ": "Aquilae",
    "パナッピュ": "Panapyu",
    "ペリュイヌ": "Peruine",
    "シルバーナ": "Silvana",
    "ポルースカ": "Poruska",
    "ナシュレク": "Nashlek",
    "セッチャー": "Setcher",
    "ハイクラム": "Haikram",
    "シャントン": "Shanton",
    "プレーリー": "Prairie",
    "ココッチャ": "Cococha",
    "ファルパパ": "Falpapa",
    "うしのふん": "Cowpat",
    "ジグネール": "Zignel",
    "プリフィー": "Prifie",
    "ビュブロス": "Byblos",
    "オルストフ": "Orstov",
    "エルノーラ": "Elnora",
    "キュレクス": "Kyurex",
    "ランガーオ": "Langao",
    "オルフェア": "Orphea",
    "ギルザッド": "Gilzad",
    "こがねいろ": "golden",
    "フォレスト": "forest",
    "マスカット": "muscat",
    "ジャングル": "jungle",
    "サンセット": "sunset",
    "ガーネット": "garnet",
    "オズモンド": "Osmond",
    "ブルリア星": "Planet Brullia",
    "ウェルナー": "Werner",
    "アラーニャ": "Aranya",
    "ポエーツォ": "Poezzo",
    "エリーシェ": "Elishe",
    "ヤンディー": "Yandey",
    "アリーモス": "Alimos",
    "ナーウェイ": "Naawei",
    "ピルフォン": "Pilfon",
    "プラットル": "Platol",
    "チャーロン": "Charon",
    "ジャッカル": "Jackal",
    "ジョスリン": "Joslyn",
    "アベーシャ": "Abesha",
    "ニョッププ": "Nyopup",
    "マルジャン": "Marjan",
    "シャーヤー": "Shayer",
    "ウーウェル": "Oowell",
    "フォッチャ": "Foccia",
    "インジェラ": "Injera",
    "アルトゥナ": "Altuna",
    "ディーコン": "Deacon",
    "ビッティス": "Bittis",
    "リーフィヤ": "Leafia",
    "ディナーラ": "Dinara",
    "ガスティン": "Gastin",
    "フィーリア": "Philia",
    "フォンレイ": "Fonley",
    "ライヴァス": "Laivas",
    "ノグリッド": "Nogrid",
    "ウェダガン": "Wedgan",
    "ズィディリ": "Zidiri",
    "カーリーナ": "Karina",
    "ピロリアン": "Pylori",
    "ラファーヌ": "Rafane",
    "ジャムラン": "Jamran",
    "ギルビィス": "Gilvis",
    "ジョレミー": "Joremy",
    "シィジャン": "Shijan",
    "フィービー": "Phoebe",
    "スコルピィ": "Scorpi",
    "リュシオル": "Luciol",
    "エグバート": "Egbert",
    "ミルフィプ": "Mirfpu",
    "ガングリー": "Gangri",
    "ギャスパー": "Gasper",
    "アガッツィ": "Agazzi",
    "トゥルキス": "Turkis",
    "ウォッサム": "Wassam",
    "キャプシン": "Capsin",
    "レイリィー": "Laylee",
    "アリューロ": "Alluro",
    "トゥループ": "Tolupu",
    "リューシャ": "Ryusha",
    "シャーニャ": "Shanya",
    "ヂュロリー": "Durory",
    "ニューチョ": "Nyucho",
    "タルコット": "Talcot",
    "アシュレー": "Ashlei",
    "アレクセイ": "Alexei",
    "ジュレット": "Julet",
    "むきーっ！": "Argh!",
    "つかうもの": "items",
    "ディオーレ": "Diore",
    "ゴーレック": "Golek",
    "エイブラム": "Abram",
    "ジャーミィ": "Jammy",
    "デュレーク": "Durak",
    "ラーディス": "Ladis",
    "エンドール": "Endor",
    "カフェラテ": "latte",
    "しろはなだ": "white",
    "ジャルジャ": "Jalja",
    "ウェルジー": "Welge",
    "スーティー": "Sutei",
    "プティット": "Petit",
    "リュウトウ": "Ryuto",
    "ヌーティフ": "Nutif",
    "アーニャー": "Annya",
    "リッシュウ": "Rishu",
    "カーティス": "Katis",
    "ボーディス": "Bodis",
    "ブリッシュ": "Blish",
    "ディーリア": "Delia",
    "フォーリィ": "Foley",
    "ジョーンズ": "Jones",
    "アンヴァー": "Amber",
    "ノービック": "Nobik",
    "リーフィー": "Leafy",
    "ジェイダー": "Jayda",
    "エッキョウ": "Ekkyo",
    "オーディス": "Odis",
    "ピューリィ": "Pury",
    "アンジュー": "Anju",
    "エイジャス": "Ajas",
    "『いのる』": "pray",
    "オンライン": "online",
    "ベジセルク": "Cucumberserk",
    "夜狐セット": "Nightfox Outfit",
    "ザオトーン": "Seal Zing",
    "レグナード": "Regnad",
    "アイディア": "idea",
    "バージョン": "version",
    "エネルギー": "energy",
    "コレクター": "collector",
    "ユーちゃん": "Lizy",
    "裁縫素材屋": "Sewing Material Shop",
    "キャンセル": "cancel",
    "ザラキーマ": "Kathwack",
    "イオマータ": "Kablam",
    "ギガデイン": "Kazap",
    "ライデイン": "Zapple",
    "ジゴデイン": "Kazapstrophe",
    "コルレーン": "Colrane",
    "デザイン画": "design sketch",
    "何もしない": "Do nothing",
    "青の騎士団": "Blue Brigade",
    "滅浄の大光": "Purging Pulse",
    "モモンガ族": "Squirril",
    "バントリユ": "Bantryu",
    "スクアーロ": "Squalo",
    "リィンカネ": "Re[in]carnation",
    "白銀の死神": "Silver Slayer",
    "キャンドル": "candle",
    "プリズラン": "Jailrun",
    "マイハウス": "My House",
    "ツボ錬金部": "Pot Alchemy Club",
    "道具鍛冶部": "Toolsmithing Club",
    "武器鍛冶部": "Weaponsmithing Club",
    "防具鍛冶部": "Armorsmithing Club",
    "ジョロッチ": "Stickle",
    "悠久の金庫": "Time Capsule",
    "ぬいぐるみ": "plushie",
    "仮装メイク": "disguise makeup",
    "大富豪協会": "Tycoon Club",
    "ランキング": "ranking",
    "フェリシア": "Felicia",
    "メタル迷宮": "Metal Maze",
    "元気タイム": "Bonus Time",
    "ドルゴール": "Dol Radio",
    "ついてクン": "Pet",
    "シャレマネ": "Mimicker",
    "ダンジョン": "dungeon",
    "イザヤール": "Aquila",
    "パティシエ": "pastry chef",
    "クァバルナ": "Kukulkannibal",
    "天魔黙示録": "Kukulkannibapocalypse",
    "サバイバル": "survival",
    "勇気の石塔": "Pillar of Courage",
    "ガルドドン": "Gardodon",
    "ローガスト": "Logast",
    "ラティーフ": "Lateef",
    "ドラゴラム": "Puff",
    "ぼっちゃま": "young master",
    "エッちゃん": "Estie",
    "レストリア": "Restoria",
    "アマラーク": "Amarak",
    "ラランブラ": "Larambla",
    "シュタール": "Stahl",
    "バシルーラ": "Bazoom",
    "クバーラト": "Kubarat",
    "ネーしゃま": "Zenny",
    "ヒューくん": "Hyuzie",
    "レジェンズ": "Legends",
    "親密レベル": "Bond Level",
    "管理端末": "Management Terminal",
    "軍司令部": "Army Headquarters",
    "神の緋石": "Divine Crimsonite",
    "ヌレギヌ": "false accusation",
    "叡智の冠": "Crown of Wisdom",
    "チャゴス": "Prince Charmles",
    "魔物使い": "Monster Master",
    "覇者の心": "Champion Heart",
    "大魔瘴期": "Age of Miasma",
    "どくばり": "Poison Needle",
    "魔法戦士": "armamentalist",
    "勇者の盾": "Hero's Shield",
    "月見団子": "Moon Dumpling",
    "メラゾ熱": "Kafrizz Fever",
    "たけやり": "Bamboo Spear",
    "ねこひげ": "Cat Whiskers",
    "やくそう": "Medicinal Herb",
    "ながぐつ": "Rubber Boots",
    "バトマス": "battlemaster",
    "マシン系": "Machine-type",
    "異界滅神": "Otherworldly Obliterator",
    "聖騎士団": "Holy Knights",
    "バザー客": "Bazaar Guest",
    "迷いの霧": "magical mist",
    "戦神の箱": "War God Box",
    "ゾンビ系": "Zombie-type",
    "悲運の王": "Tragic King",
    "道具使い": "Item Master",
    "だいだい": "sour orange",
    "うぐいす": "green-brown",
    "バシっ娘": "Bazoom Girl",
    "ホハフホ": "Hohahuho",
    "ヘヘヒヒ": "Hehehihi",
    "ハフフハ": "Hahuhuha",
    "ヘヘヘパ": "Hehehepa",
    "こんぼう": "Oaken Club",
    "せいすい": "Holy Water",
    "雪の女王": "Snow Queen",
    "こげちゃ": "dark brown",
    "クチナシ": "Kuchinashi",
    "マツノシ": "Matsunoshi",
    "ぶとうぎ": "Strongsam",
    "ハネツキ": "Hanetsuki",
    "タツノギ": "Tatsunogi",
    "暗黒大樹": "Dark Tree",
    "しゅいろ": "vermilion",
    "しらあい": "pale cyan",
    "しっこく": "jet black",
    "うめねず": "pale plum",
    "のうこん": "deep blue",
    "ペレチカ": "Perechika",
    "シラタマ": "Shiratama",
    "マルツネ": "Marutsune",
    "ナワシロ": "Nawashiro",
    "シンリツ": "Shinritsu",
    "シラクモ": "Shirakumo",
    "イワノフ": "Stoneberg",
    "マガネリ": "Maganelli",
    "ネグシド": "Negushido",
    "マツリカ": "Matsurika",
    "ビコメチ": "Bikomechi",
    "ツキカゲ": "Tsukikage",
    "シロベニ": "Shirobeni",
    "カサリン": "Catherine",
    "シグネロ": "Shigunero",
    "ニシホタ": "Nishihota",
    "マネキン": "mannequin",
    "マツシム": "Matsushim",
    "カラタチ": "Karatachi",
    "ミチシオ": "Michishio",
    "ゾーン技": "Pep Power",
    "迷宮の主": "Maze Boss",
    "戦士バン": "Warrior Ban",
    "きんかい": "Gold Bar",
    "かくとく": "received",
    "ピナヘト": "Pinahett",
    "タケトラ": "Taketora",
    "トヨホロ": "Toyohoro",
    "バルーク": "Balouque",
    "オリリン": "Ori Wori",
    "ダビヤガ": "Dabiyaga",
    "ツスクル": "Tsusukul",
    "ふじいろ": "wisteris",
    "モモンガ": "Squirril",
    "すごろく": "Sugoroku",
    "ローテル": "Routelle",
    "ロルフク": "Roarfolk",
    "マーギル": "Margille",
    "クロトビ": "Kurotobi",
    "ペラトネ": "Peratone",
    "チアマト": "Chiamato",
    "ミシェル": "Michelle",
    "カルカヤ": "Karukaya",
    "クマタカ": "Kumataka",
    "タマズサ": "Tamazusa",
    "ウツセミ": "Utsusemi",
    "ハナサト": "Hanasato",
    "カヤカリ": "Kayakari",
    "ヤマブキ": "Yamabuki",
    "セペフル": "Sepefuru",
    "ホソバミ": "Hosobami",
    "ゼレニナ": "Zelenina",
    "マノリタ": "Manorita",
    "レポリニ": "Repolini",
    "ヒキワリ": "Hikiwari",
    "ハバネロ": "Habanero",
    "シロタエ": "Shirotae",
    "トントト": "Tonototo",
    "ヤルミラ": "Yarumira",
    "ユリユリ": "Yuriyuri",
    "タルタタ": "Tarutata",
    "バテルス": "Batterus",
    "ミシダン": "Mishidan",
    "ユシレピ": "Yusirepi",
    "ノミギリ": "Nomigiri",
    "ニノヤズ": "Ninoyazu",
    "バチコワ": "Bachkova",
    "パパルパ": "Papalupa",
    "モニモニ": "Monimoni",
    "フハホフ": "Huhahofu",
    "テテネネ": "Tetenene",
    "ハリカラ": "Harikara",
    "ミリシェ": "Milliche",
    "レダナト": "Redanato",
    "ククコリ": "Kukukori",
    "ヤムジク": "Yamujiku",
    "ムタデマ": "Mutadema",
    "ボルリラ": "Borrilla",
    "ジヌデル": "Shinderu",
    "パマテラ": "Pamatera",
    "プクヨミ": "Pukuyomi",
    "サクニナ": "Sakunina",
    "カトレヤ": "Cateleya",
    "パピリポ": "Papiripo",
    "ハジカミ": "Hajikami",
    "ポポヘプ": "Popohepu",
    "ナポポフ": "Napopofu",
    "アニバス": "Annivers",
    "サリベス": "Sarybeth",
    "ミズッチ": "Mizucchi",
    "ルーシア": "Orifiela",
    "シシーラ": "Shishira",
    "パピヨン": "Papillon",
    "マジパン": "Marzipan",
    "ぺネロぺ": "Penelope",
    "ジアツク": "Jiatsuku",
    "パメッチ": "Pametchi",
    "タラクハ": "Tarakuha",
    "ヒナギク": "Hinagiku",
    "イチジク": "Ichijiku",
    "アカマツ": "Akamatsu",
    "ヒキシオ": "Hikishio",
    "せんれき": "Records",
    "ふくびき": "Lottery",
    "テンの日": "Ten Day",
    "ウラード": "Woolard",
    "セトリー": "Setorii",
    "ヴェキオ": "Vecchio",
    "バスラー": "Bassler",
    "ロッサム": "Rossham",
    "ベリンダ": "Belinda",
    "ナドラガ": "Nadraga",
    "ネロドス": "Nerodos",
    "ゼクレス": "Zechres",
    "ガテリア": "Gateria",
    "トルネコ": "Torneko",
    "マゼンタ": "magenta",
    "ひっさつ": "Special",
    "ランババ": "Ranbaba",
    "グルバン": "Gureban",
    "ルジアダ": "Rujiada",
    "シャペル": "Sharpel",
    "ルシール": "Lucille",
    "ボリバル": "Boliver",
    "ジガンバ": "Jiganba",
    "プリミン": "Purimin",
    "ユーネリ": "Yuuneri",
    "クーミナ": "Kuumina",
    "ケルキフ": "Kelkief",
    "パレーノ": "Palenno",
    "ルーシャ": "Rouscha",
    "カーメロ": "Karmelo",
    "リネット": "Rinetto",
    "ルゴール": "Rugolle",
    "ロゲール": "Logelle",
    "マルーノ": "Marouno",
    "ビーゼス": "Bizethe",
    "ドロンガ": "Doronga",
    "レヴェリ": "Reverie",
    "ルンココ": "Runkoko",
    "ゴーツク": "Gotsuku",
    "ポリーナ": "Paulina",
    "ピルトポ": "Piltopo",
    "カポロン": "Kaporon",
    "ポランク": "Poranku",
    "ギマール": "Guimard",
    "ガタチャ": "Gatacha",
    "ロレツオ": "Loretto",
    "ムツィコ": "Mutsico",
    "ヘルミネ": "Hermine",
    "マリシア": "Marisha",
    "マシスタ": "Masista",
    "マヌエラ": "Manuela",
    "コンラザ": "Conraza",
    "チャジロ": "Chajiro",
    "ポレッテ": "Polette",
    "ロマヌス": "Romanus",
    "パラリン": "Pararin",
    "コアヤフ": "Koayafu",
    "ウラジロ": "Urajiro",
    "ポロペン": "Poropen",
    "ペリトン": "Periton",
    "ベラチャ": "Beracha",
    "バルトロ": "Bartolo",
    "ペリンタ": "Perinta",
    "ペピール": "Pepeelu",
    "アルキパ": "Archipa",
    "ピンドフ": "Pindoff",
    "パプラム": "Papulam",
    "ゲラジム": "Gerajim",
    "ゴラトム": "Goratom",
    "ペリレネ": "Pelileo",
    "ムチョロ": "Mucholo",
    "タルカド": "Talcado",
    "グラガド": "Gragado",
    "プッチン": "Pucchin",
    "アナベル": "Annabel",
    "カミッラ": "Camilla",
    "ラプラド": "Laprado",
    "シェラタ": "Chelata",
    "アユカケ": "Ayukake",
    "オダマキ": "Odamaki",
    "ピノッピ": "Pinoppi",
    "マダラキ": "Madraki",
    "ポッカラ": "Pokkara",
    "セネット": "Senette",
    "ラドニア": "Ladonia",
    "ユナバル": "Yunabal",
    "ヒメネス": "Himenes",
    "ラニエロ": "Raniero",
    "ポリッピ": "Polippi",
    "シーシャ": "Sheesha",
    "モルーゼ": "Morusei",
    "パチュリ": "Pachuli",
    "マーロウ": "Marlowe",
    "ヌサカン": "Nusakan",
    "ミランダ": "Miranda",
    "ベスリン": "Bethlin",
    "リトリア": "Litoria",
    "ヘギンツ": "Hegints",
    "ポピリア": "Popilia",
    "チャガナ": "Chagana",
    "クレセダ": "Creseda",
    "シュルリ": "Shururi",
    "ヌンタタ": "Nuntata",
    "ププルン": "Pupurun",
    "アメノナ": "Amenona",
    "ジリカン": "Jirikan",
    "ポミリン": "Pomirin",
    "ソシェラ": "Sochera",
    "ゾゼルグ": "Zozelgu",
    "ボナール": "Bonnard",
    "リカルド": "Ricardo",
    "サタタン": "Satatan",
    "パーシリ": "Pashiri",
    "ミミング": "Mimingu",
    "シュクル": "Shukuru",
    "ミニタン": "Minitan",
    "ニャポー": "Meowpaw",
    "ソマルカ": "Somarka",
    "ドラデア": "Doradea",
    "シャフル": "Shuffle",
    "リバイバ": "Ribaiba",
    "ブノワト": "Bunwato",
    "ビゴスラ": "Bigosla",
    "アレカヒ": "Arekahi",
    "マーシト": "Mashito",
    "モフテカ": "Mofteka",
    "マグリル": "Magrill",
    "ビリャロ": "Villaro",
    "マギダス": "Magidas",
    "メテオラ": "Meteora",
    "サショラ": "Sashola",
    "アサキバ": "Asakiba",
    "ププリン": "Pupurin",
    "テンオツ": "Tenotsu",
    "マヤギン": "Mayagin",
    "ビナッテ": "Vinatte",
    "パラポン": "Parapon",
    "ワシコフ": "Wasikov",
    "コロペン": "Coropen",
    "ミャダバ": "Myadaba",
    "ラメルヌ": "Ramerne",
    "トーリナ": "Torinna",
    "ヒョコタ": "Hyokota",
    "ナナリー": "Nanalee",
    "ガスペロ": "Gaspero",
    "ランバル": "Ranbaru",
    "チュカカ": "Chukaka",
    "カンココ": "Kancoco",
    "ペタチョ": "Petacho",
    "プルンパ": "Purunpa",
    "レレッポ": "Releppo",
    "ラネッタ": "Lanetta",
    "バラギル": "Balagir",
    "ソノラン": "Sonoran",
    "ヒメウズ": "Himeuzu",
    "メルテナ": "Meltena",
    "ゴンガロ": "Gongaro",
    "セオラン": "Theoran",
    "ガシャリ": "Gashari",
    "リステア": "Listeah",
    "トカチャ": "Tokacha",
    "カランテ": "Carante",
    "ミグニネ": "Mignine",
    "ロミルダ": "Romilda",
    "ルペッタ": "Ruperta",
    "シャニス": "Chanice",
    "アガジル": "Agajiru",
    "ナクダス": "Nakudas",
    "ゼゼンデ": "Zezende",
    "メビシェ": "Mebishe",
    "バロケル": "Barokel",
    "ベデゼル": "Bedezel",
    "デオルケ": "Deorque",
    "ブルベラ": "Brubera",
    "ズオナロ": "Zuonaro",
    "スニフル": "Sniffle",
    "ガルダモ": "Gardamo",
    "マビシア": "Mabicia",
    "チャリリ": "Chariri",
    "シャポラ": "Shapora",
    "デスピナ": "Despina",
    "ラリッサ": "Larissa",
    "シーラナ": "Shirana",
    "セルニタ": "Selnita",
    "ガドッソ": "Gadosso",
    "デプラセ": "Deprase",
    "トッケロ": "Tokkero",
    "ペペルポ": "Peperpo",
    "ペポリス": "Pepolis",
    "パポスヤ": "Paposya",
    "ルワーレ": "Ruwarei",
    "サパラン": "Saparan",
    "パロンタ": "Paronta",
    "ミラベル": "Mirabel",
    "パサンタ": "Pasanta",
    "ホフマン": "Hoffman",
    "ガボリス": "Gaboris",
    "マミロン": "Mamiron",
    "ヒラリス": "Hilaris",
    "ビヨンサ": "Beyonsa",
    "パジラス": "Pajiras",
    "トントネ": "Tontone",
    "ヒツァタ": "Hizzata",
    "ヒぺーナ": "Hippena",
    "ポポタン": "Popotan",
    "ヘプット": "Heputto",
    "ノレエレ": "Noreele",
    "タカチャ": "Takacha",
    "バレンケ": "Barenke",
    "シロップ": "Shiropp",
    "ポワソン": "Poisson",
    "シグーノ": "Shiguno",
    "ロヨバン": "Royoban",
    "グズガス": "Guzugas",
    "グレリオ": "Gurerio",
    "ルオパリ": "Ruopari",
    "スイプト": "Suiputo",
    "ぺルソン": "Peruson",
    "パレルモ": "Palermo",
    "メギピオ": "Megipio",
    "ペラトン": "Peraton",
    "カムヤプ": "Kamyapu",
    "ムタンド": "Mutando",
    "カワチィ": "Kawachi",
    "シフォン": "Chiffon",
    "セルリー": "Saralee",
    "ブラニコ": "Branico",
    "ローラン": "Laurent",
    "グリッタ": "Glitter",
    "パラツォ": "Palazzo",
    "ボラチャ": "Boracha",
    "オモダカ": "Omodaka",
    "ザガゾン": "Zagazon",
    "ベルギル": "Bergill",
    "ピロッテ": "Pilotte",
    "ポッピロ": "Poppiro",
    "メリッサ": "Melissa",
    "ウルミダ": "Urumida",
    "ロザリー": "Rosalie",
    "ギヨッテ": "Giyotte",
    "フラノワ": "Flannoy",
    "ハクチャ": "Hakucha",
    "シードル": "Shidoru",
    "ゴッテス": "Gottess",
    "ボルンガ": "Borunga",
    "イッテツ": "Ittetsu",
    "ゼラリム": "Zelarim",
    "レーニエ": "Rainier",
    "レンドア": "Lendor",
    "エテーネ": "Ethene",
    "キンベル": "Kimbel",
    "エルトナ": "Eltona",
    "アグラニ": "Agrani",
    "ワタクシ": "myself",
    "エルドナ": "Eldona",
    "マリーヌ": "Marine",
    "カシャル": "Kashal",
    "ヘペット": "Heppet",
    "ラグアス": "Raguas",
    "ボーレン": "Vollen",
    "プスゴン": "Pusgon",
    "ダストン": "Duston",
    "ホッツィ": "Hottsi",
    "キンナー": "Kinner",
    "ザイガス": "Sigras",
    "エリーゴ": "Eriego",
    "ネルゲル": "Nergel",
    "ザイナー": "Zeiner",
    "ベドラー": "Bedora",
    "ポーリア": "Paulia",
    "ダドリー": "Dudley",
    "ゴリウス": "Gorius",
    "キルギル": "Kirgyl",
    "ムーニス": "Moonis",
    "アブタル": "Abutar",
    "ブレンダ": "Brenda",
    "カブース": "Kabusu",
    "ファズマ": "Phasma",
    "グリモス": "Grimos",
    "ビノービ": "Binobi",
    "ナダイア": "Nadaia",
    "モッキン": "Mockin",
    "エメリヤ": "Emelia",
    "フェリナ": "Felina",
    "パルミオ": "Palmio",
    "ゼルメア": "Zelmea",
    "ゾブリス": "Zobris",
    "ショーナ": "Shauna",
    "カルーモ": "Carumo",
    "グロリス": "Gloris",
    "ランドン": "Landon",
    "オルセコ": "Orseco",
    "ナルビア": "Nalbia",
    "ナシーム": "Naseem",
    "オレンジ": "orange",
    "ポイズン": "poison",
    "イエロー": "yellow",
    "まっちゃ": "matcha",
    "カナリヤ": "canary",
    "パープル": "purple",
    "コルチョ": "Kolcho",
    "ネーモン": "Neymon",
    "クアメル": "Kuamel",
    "ツアロム": "Tuarom",
    "アレグム": "Aregum",
    "パリエス": "Paries",
    "アーシー": "Arshie",
    "ルバート": "Rubart",
    "チョリス": "Chorus",
    "パリュス": "Paruse",
    "ルアンベ": "Ruanbe",
    "ナーミス": "Narmis",
    "クイーレ": "Quaile",
    "ノースト": "Nouste",
    "ソマーク": "Somark",
    "タージオ": "Targio",
    "スリーズ": "Sleaze",
    "フレーツ": "Fleets",
    "リアータ": "Riatta",
    "ミーリュ": "Mieryu",
    "キーエル": "Kielle",
    "ルーベム": "Ruubem",
    "ケーラン": "Keyran",
    "カリート": "Calito",
    "サーンハ": "Saanha",
    "ザングル": "Zangle",
    "ロンリア": "Lonria",
    "エブラフ": "Ebluff",
    "ジルジャ": "Jiruja",
    "マハート": "Mahart",
    "ミッケル": "Mickel",
    "デリアン": "Derian",
    "プルンガ": "Plunga",
    "ホルサス": "Horsus",
    "オルパナ": "Orpana",
    "スプイト": "Supito",
    "ロロップ": "Lollop",
    "ペラーナ": "Perana",
    "ピースペ": "Pisupe",
    "マウタス": "Mautas",
    "ルオパス": "Luopus",
    "パープナ": "Papuna",
    "アムサリ": "Amsari",
    "シャミー": "Shammy",
    "カナーテ": "Canate",
    "ワージタ": "Wajita",
    "ユリーラ": "Yurila",
    "チャリオ": "Chario",
    "ヤッコイ": "Yakkoi",
    "クアライ": "Quarai",
    "ロオチャ": "Loocha",
    "ムントフ": "Muntov",
    "フウザム": "Fuuzam",
    "トッチァ": "Toccia",
    "アッカフ": "Akkafu",
    "モルテン": "Molten",
    "マッケイ": "Mackay",
    "フィギン": "Figgin",
    "セリータ": "Serita",
    "グルマン": "Gulman",
    "ギャンパ": "Gyanpa",
    "コーレス": "Corres",
    "ゲンバウ": "Genbau",
    "カトラズ": "Katraz",
    "バッゲス": "Bagges",
    "イザヨイ": "Izayoi",
    "パーラプ": "Parlap",
    "シャリア": "Sharia",
    "ロアチュ": "Roacha",
    "シュシュ": "Shushu",
    "パムック": "Pamuku",
    "ベルガウ": "Belgau",
    "ルヤーナ": "Luyana",
    "ケパルト": "Kepart",
    "ボオレン": "Booren",
    "レザール": "Lazare",
    "チャミミ": "Chamim",
    "ホウガイ": "Hougai",
    "ベニヒナ": "Beniha",
    "セーケン": "Seiken",
    "ルリーズ": "Luriez",
    "キャミラ": "Kamira",
    "エズメラ": "Esmera",
    "ナリーン": "Narine",
    "ダヌシュ": "Danush",
    "フダード": "Fudado",
    "バッフル": "Baffle",
    "ポッポル": "Poppol",
    "キフライ": "Kifley",
    "レゴーム": "Legome",
    "ノクター": "Noctor",
    "ハサーレ": "Hasare",
    "バンシェ": "Banshe",
    "キシュレ": "Kishre",
    "ジョハリ": "Johari",
    "レリアン": "Lerian",
    "クートー": "Kurtor",
    "シッキム": "Sikkim",
    "セモーナ": "Semona",
    "シャウラ": "Shaula",
    "シェトリ": "Shetry",
    "ルクーバ": "Lucuba",
    "ヘミング": "Heming",
    "ドンダム": "Dondam",
    "ミナリー": "Minari",
    "クダント": "Kudant",
    "コホーザ": "Cohoza",
    "エルミナ": "Elmina",
    "クラッサ": "Kurasa",
    "ミルーラ": "Mirula",
    "ロッペン": "Roppen",
    "ボロディ": "Borody",
    "サティナ": "Satina",
    "カプラン": "Kaplan",
    "ディリロ": "Dirilo",
    "アニッタ": "Anitta",
    "エレーヌ": "Elaine",
    "デコリー": "Decory",
    "タルバス": "Talbus",
    "バーキン": "Birkin",
    "フロイデ": "Freude",
    "クアンナ": "Quanna",
    "シオラン": "Cioran",
    "スラリー": "Suraly",
    "マティラ": "Matira",
    "ダツィン": "Datsin",
    "ティリリ": "Tiriri",
    "プップル": "Pupple",
    "ルールナ": "Luluna",
    "カチュア": "Kachua",
    "ディモス": "Deimos",
    "グログス": "Gulgus",
    "ポリーヌ": "Poline",
    "フェニア": "Phenia",
    "ヒャッカ": "Hyakka",
    "バガトゥ": "Bagatu",
    "ガラトゥ": "Garatu",
    "ゴルアガ": "Golaga",
    "キュット": "Kyutto",
    "エルメメ": "Elmeme",
    "イリズヤ": "Irizya",
    "ピティカ": "Pitica",
    "ミヨウル": "Miyoru",
    "ラダディ": "Ladadi",
    "アスケン": "Asuken",
    "パストン": "Paston",
    "カイラム": "Kairam",
    "パルーラ": "Parula",
    "ラベロー": "Rabero",
    "モスコル": "Moscol",
    "クラバン": "Kraban",
    "ホッチャ": "Hotcha",
    "ガルキス": "Garkis",
    "ルビオン": "Rubion",
    "コライユ": "Koraiu",
    "ニオキス": "Niokis",
    "ケンドル": "Kendol",
    "トーマス": "Toumas",
    "マローア": "Malora",
    "プランセ": "Planse",
    "ユジュヤ": "Yujuya",
    "ムントン": "Munton",
    "カローズ": "Kaloze",
    "エパニエ": "Epanie",
    "ヤゴット": "Yagott",
    "トルソー": "Toruso",
    "ズケティ": "Zuketi",
    "バルザイ": "Balzai",
    "サントン": "Santon",
    "オリビア": "Olivia",
    "ジャベリ": "Javeri",
    "リドバン": "Lidban",
    "ターブリ": "Taburi",
    "ウイロウ": "Willow",
    "シュウラ": "Shuura",
    "カリウス": "Carius",
    "カザルス": "Casals",
    "サレーマ": "Salema",
    "セステル": "Cestel",
    "ゴルスラ": "Gemsly",
    "カッシュ": "Kasshu",
    "リアンナ": "Lianna",
    "ロブソン": "Robson",
    "クーパー": "Cooper",
    "ビルラー": "Biller",
    "ウロゾス": "Urozos",
    "マルセン": "Marsen",
    "ドリアス": "Dorias",
    "ラカーナ": "Lacana",
    "ハズカム": "Hazcam",
    "モルガン": "Morgan",
    "プルツコ": "Plutko",
    "チャタオ": "Chatao",
    "ゴッツオ": "Gotsuo",
    "ルセット": "Ruseto",
    "パルーン": "Paloon",
    "グレシア": "Grecia",
    "チェボン": "Chebon",
    "レサニー": "Lesani",
    "キーラル": "Keeral",
    "ザンドス": "Zandos",
    "ゼルマド": "Zelmad",
    "グルジャ": "Ghulja",
    "カマアタ": "Kamata",
    "キジール": "Kizier",
    "ドーニラ": "Donila",
    "ランギー": "Langie",
    "ブシュラ": "Bushra",
    "エドメク": "Edomek",
    "ザブラル": "Zabral",
    "ゼドリグ": "Zedrig",
    "ビスリン": "Bislin",
    "トリーナ": "Torina",
    "レズリー": "Leslie",
    "ジャメフ": "Jamefu",
    "カラーマ": "Kalama",
    "トゥフラ": "Tufura",
    "ワルダー": "Walder",
    "ターラタ": "Tarata",
    "ベゼード": "Bezedo",
    "デニエス": "Denies",
    "アバノク": "Abanoc",
    "パッフル": "Paffle",
    "イヨルカ": "Iyorka",
    "ミガンス": "Migans",
    "ケディヤ": "Kediya",
    "ズグラム": "Zugram",
    "ビンチュ": "Bincho",
    "グーボレ": "Gubole",
    "ネゾンネ": "Nezone",
    "ジグロウ": "Jiguro",
    "ターニス": "Tannis",
    "ボラデュ": "Boradu",
    "アレイダ": "Aleida",
    "ニジャル": "Nushal",
    "ビノアス": "Vinoas",
    "モーデン": "Morden",
    "メビータ": "Mebita",
    "リギョス": "Rigyos",
    "キージラ": "Kijira",
    "グナクー": "Gunaku",
    "シーギア": "Shigia",
    "ビョルツ": "Bjortz",
    "ドロフィ": "Dorofi",
    "ノーテス": "Notess",
    "メイデル": "Maidel",
    "セイラン": "Seiran",
    "ハクドウ": "Hakudo",
    "マッカル": "McCull",
    "グレンダ": "Glenda",
    "セリャン": "Serian",
    "シャッデ": "Shadde",
    "フロイダ": "Froida",
    "コトノハ": "Kotono",
    "ボンゴス": "Bongos",
    "ルモンド": "Remond",
    "レターヌ": "Letann",
    "リオンネ": "Rionne",
    "トゥバン": "Thuban",
    "セテーラ": "Setera",
    "パーポフ": "Papofu",
    "ユーニス": "Eunice",
    "ポンヌク": "Ponnuk",
    "ピッペル": "Pippel",
    "ガルニー": "Garnie",
    "ムタタプ": "Muttap",
    "ルアンべ": "Luambe",
    "ルキーノ": "Lukino",
    "メレーヌ": "Melene",
    "サビーラ": "Sabira",
    "フレデリ": "Fredri",
    "テリップ": "Teripp",
    "キャプン": "Kyapun",
    "プンペン": "Punpen",
    "べニーズ": "Benize",
    "コオモス": "Coomos",
    "ラアドワ": "Radowa",
    "セリーヌ": "Celine",
    "ネイシャ": "Neisha",
    "プロシオ": "Proshi",
    "レリーン": "Leleen",
    "クータス": "Kootas",
    "ロレンス": "Laurel",
    "スコット": "Hardie",
    "ヤズーダ": "Yazuda",
    "ポスタン": "Postan",
    "ミュッカ": "Myukka",
    "ナイリア": "Nairia",
    "ガガオス": "Gagaos",
    "ジンダス": "Jindas",
    "ビリッグ": "Biligg",
    "チィクア": "Chikua",
    "メルルフ": "Melurf",
    "リコリー": "Ricoly",
    "ドライト": "Dright",
    "ギッドン": "Giddon",
    "シェリー": "Sherry",
    "カッチュ": "Katchu",
    "ラライヤ": "Laraya",
    "フリップ": "Furipp",
    "カンポン": "Kanpon",
    "パステル": "Pastel",
    "アプリコ": "Aprico",
    "サビーヌ": "Sabine",
    "ナビーノ": "Nabino",
    "グレッサ": "Gressa",
    "サッケス": "Sakkes",
    "バキーン": "Bakeen",
    "ピルトン": "Pilton",
    "プープル": "Pupuru",
    "プルペア": "Prupea",
    "ミチョム": "Michom",
    "オシエム": "Oshiem",
    "ムシュコ": "Mushko",
    "ヴェネタ": "Veneta",
    "プシャン": "Pushan",
    "エミリオ": "Emilio",
    "フリゾン": "Frizon",
    "ルイース": "Louise",
    "キトリー": "Kitoli",
    "サガール": "Sagaar",
    "ワドワー": "Wadowa",
    "メローメ": "Melome",
    "アニック": "Annick",
    "ダミーニ": "Damini",
    "チェツア": "Chetua",
    "グッタル": "Guttal",
    "シーンネ": "Shinei",
    "レーテュ": "Reityu",
    "シーヴェ": "Shivei",
    "クリーズ": "Kurize",
    "アマリア": "Amalia",
    "エルネリ": "Erneri",
    "バウンズ": "Baunze",
    "トニオス": "Tonios",
    "ブルダル": "Buldar",
    "ケルビス": "Kervis",
    "アリシス": "Alisis",
    "ズッサム": "Zussam",
    "モスコウ": "Moscou",
    "バートン": "Barton",
    "ヤッチェ": "Yatche",
    "パパーナ": "Papana",
    "バッドン": "Baddon",
    "ドドリス": "Dodris",
    "ハンチャ": "Hancha",
    "ホオズキ": "Houzuki",
    "ホーリス": "Horiss",
    "ムスチー": "Muschi",
    "ダニエル": "Daniel",
    "バルトル": "Baltor",
    "メドゥナ": "Meduna",
    "エゾマツ": "Spruce",
    "シルバー": "silver",
    "ハクール": "Hakure",
    "ポルルプ": "Porrup",
    "ペープペ": "Pepupe",
    "バトエン": "Batoen",
    "アズラン": "Azlan",
    "さくせん": "Misc.",
    "たいまつ": "Torch",
    "じゅもん": "spell",
    "にんげん": "human",
    "ニンゲン": "human",
    "ミトラー": "Mitra",
    "リリーエ": "Lilie",
    "エイドス": "Eidos",
    "マンマー": "Momma",
    "ゼーベス": "Zebes",
    "バルドル": "Baldr",
    "フレイヤ": "Freya",
    "ユービア": "Yubia",
    "バーティ": "Buttre",
    "シガール": "Sigal",
    "ジュアロ": "Juaro",
    "ドランド": "Drand",
    "ジュレド": "Juled",
    "ウルベア": "Urbea",
    "ルシュカ": "Ruska",
    "クリーム": "cream",
    "ブラッド": "blood",
    "ベージュ": "beige",
    "スチール": "steel",
    "むらさき": "grape",
    "アリーナ": "Arena",
    "イヴロム": "Ivrom",
    "ズワルド": "Zwald",
    "アーダン": "Ardan",
    "クローブ": "Clove",
    "イジウス": "Ijius",
    "ムルーノ": "Murno",
    "ラージャ": "Raja",
    "シャーム": "Shamu",
    "オーシェ": "Oushe",
    "ノーワス": "Novas",
    "アーグス": "Argus",
    "ナービュ": "Nabyu",
    "イニーナ": "Inina",
    "オービエ": "Orbie",
    "フランク": "Frank",
    "リフィト": "Rifit",
    "メアリス": "Maris",
    "チャック": "Chuck",
    "エディス": "Edith",
    "レーライ": "Lerai",
    "ジューノ": "Jouno",
    "リーヴィ": "Leevy",
    "ゼイビー": "Zeibi",
    "ザイリー": "Zeiri",
    "ヤービィ": "Yabby",
    "キューラ": "Keura",
    "アールフ": "Aleph",
    "ザイクス": "Zykes",
    "ザンジャ": "Zanja",
    "ディノム": "Dinom",
    "ニロップ": "Nirop",
    "プリュノ": "Pruno",
    "プルリィ": "Purly",
    "スピーラ": "Spira",
    "ペルジュ": "Perju",
    "アーペル": "Arpel",
    "ニューネ": "Newne",
    "メーロル": "Merol",
    "サアタウ": "Satau",
    "ツィッサ": "Zissa",
    "ラツィフ": "Ratif",
    "ツェンケ": "Zenke",
    "チョスウ": "Chosu",
    "グレック": "Greck",
    "ティルダ": "Tilda",
    "チュケェ": "Chuke",
    "ジュロム": "Jurom",
    "シュリィ": "Shuri",
    "プレーテ": "Prete",
    "セルーソ": "Celso",
    "フアーナ": "Fuana",
    "チョムウ": "Chomu",
    "クアトオ": "Kuato",
    "キイチョ": "Kicho",
    "ヤップイ": "Yapui",
    "ポナック": "Ponak",
    "アルハン": "Alhan",
    "リューロ": "Ryuro",
    "タサール": "Tasar",
    "セティー": "Setty",
    "サーニュ": "Sannu",
    "ツィサア": "Tsisa",
    "アムチャ": "Amcha",
    "アルティ": "Aruti",
    "グラート": "Glato",
    "リオーレ": "Liore",
    "ネージュ": "Neige",
    "ブレント": "Brent",
    "オービル": "Orvil",
    "フィオレ": "Fiore",
    "フィブラ": "Fibra",
    "ミーリャ": "Milla",
    "グルード": "Grude",
    "エミーネ": "Emine",
    "カビール": "Kabir",
    "コルシュ": "Corsh",
    "フラッツ": "Flats",
    "ノーニャ": "Nonya",
    "シーナン": "Sinan",
    "リャード": "Ryard",
    "エリオス": "Elios",
    "リーニャ": "Linya",
    "ピーシャ": "Pisha",
    "ラーリア": "Laria",
    "ボリュー": "Boryu",
    "シルヴィ": "Silvy",
    "テーニャ": "Tenya",
    "プレッツ": "Pretz",
    "ローピン": "Ropin",
    "チューラ": "Chara",
    "ヴェルヌ": "Verne",
    "セヴァス": "Sevas",
    "キキョウ": "Kikyo",
    "ベニーア": "Benia",
    "ピョンル": "Ponel",
    "キャロン": "Caron",
    "シャーヌ": "Sharn",
    "シューヌ": "Shunu",
    "マインズ": "Meinz",
    "アスケル": "Asker",
    "アルギン": "Algin",
    "ユミール": "Yumir",
    "トゥルノ": "Tulno",
    "リッツェ": "Ritze",
    "タウリー": "Taury",
    "コーヴィ": "Corvi",
    "フォニオ": "Fonio",
    "ニルーナ": "Nirna",
    "ラヴィア": "Lavia",
    "エッカー": "Ecker",
    "ロナール": "Ronal",
    "シャディ": "Shadi",
    "ノーニル": "Nonil",
    "トルディ": "Tordi",
    "メイプル": "Maple",
    "ヤーヒム": "Yahim",
    "ヒーディ": "Heedy",
    "パッピイ": "Pappi",
    "ポップイ": "Popui",
    "パッツィ": "Patsy",
    "ポッツァ": "Pozza",
    "ピッチョ": "Picho",
    "ベアータ": "Beata",
    "オグバン": "Ogban",
    "カティヤ": "Katya",
    "アマティ": "Amati",
    "カーリィ": "Karry",
    "アリック": "Arick",
    "マディア": "Madia",
    "アルマス": "Armas",
    "バンリィ": "Banry",
    "アイスン": "Aisun",
    "リアーヌ": "Liann",
    "ノッツェ": "Notze",
    "マドゥン": "Madun",
    "リーベン": "Leven",
    "ランリィ": "Ranry",
    "ウェバン": "Ueban",
    "トゥーナ": "Touna",
    "ネルヴィ": "Nervi",
    "アミアン": "Amian",
    "ファンナ": "Fanna",
    "コンティ": "Conti",
    "クライト": "Krite",
    "ガシュー": "Gashu",
    "ホーシャ": "Hosha",
    "パサール": "Pasar",
    "フイーゴ": "Huigo",
    "ポピール": "Popil",
    "ストロン": "Stron",
    "エルスカ": "Elska",
    "リーベル": "Ribel",
    "ディット": "Ditto",
    "ブルバー": "Bruba",
    "ルンリィ": "Lunry",
    "モーベン": "Moben",
    "メーベル": "Mabel",
    "アルゴー": "Argou",
    "デイスン": "Dyson",
    "マウジャ": "Mauja",
    "ウロック": "Ulock",
    "メイガン": "Megan",
    "ガイノー": "Gaino",
    "プトゥン": "Putun",
    "ティサン": "Tisan",
    "トリスト": "Trist",
    "シャイラ": "Shyla",
    "ティーチ": "Tichi",
    "トッゴイ": "Togoi",
    "ルーニア": "Runia",
    "エワルト": "Ewalt",
    "ヒナゲシ": "Poppy",
    "ティグロ": "Tigro",
    "ルイッサ": "Luisa",
    "アガット": "Agato",
    "モンディ": "Mondy",
    "エーゼク": "Eizek",
    "ポトレア": "Torea",
    "ジェルノ": "Gerno",
    "ジェザム": "Jezam",
    "ミアーレ": "Miare",
    "ギジェル": "Gijel",
    "ガリュア": "Garua",
    "デリウム": "Delum",
    "ルーテア": "Lutea",
    "チャルク": "Chark",
    "ルダーン": "Rudan",
    "ブーボス": "Bubos",
    "オルソン": "Olson",
    "イグラン": "Igran",
    "マクトゥ": "Maktu",
    "オリジェ": "Orige",
    "ライジー": "Raiji",
    "ピパップ": "Pipap",
    "トゥーブ": "Toube",
    "シェルス": "Shels",
    "サットム": "Satmu",
    "アーネイ": "Arney",
    "りデーラ": "Della",
    "ドラビー": "Draby",
    "キュグニ": "Kugni",
    "リアーネ": "Liane",
    "ドランク": "Drunk",
    "ファーニ": "Fanny",
    "スケイプ": "Scape",
    "ゼーノン": "Zenon",
    "ぺイジー": "Peiji",
    "スワーニ": "Swani",
    "フリーダ": "Frida",
    "ビエーロ": "Viero",
    "クレップ": "Krepp",
    "ブロルト": "Brolt",
    "オーリン": "Oojam",
    "ダッホイ": "Dahoi",
    "ノズーボ": "Nozbo",
    "シューク": "Shuku",
    "アルナス": "Arnas",
    "セトゥル": "Setul",
    "グルーネ": "Grune",
    "ムルギー": "Murgy",
    "フリーツ": "Fritz",
    "エリーゼ": "Elize",
    "マーシィ": "Marcy",
    "イクーサ": "Ikusa",
    "マーラー": "Marla",
    "ツァラオ": "Tsaro",
    "ディビフ": "Dibif",
    "スアーレ": "Suare",
    "ミルフィ": "Mirfi",
    "ポワール": "Poire",
    "ペーシュ": "Peche",
    "ドホース": "Dohos",
    "フルーラ": "Flura",
    "アデーレ": "Adele",
    "ジャドン": "Jadon",
    "ガートゥ": "Gartu",
    "プラット": "Pratt",
    "トゥスカ": "Tuska",
    "アズナイ": "Aznai",
    "ファライ": "Farai",
    "ズィラヴ": "Zirav",
    "ランジュ": "Lange",
    "ジャミル": "Jamil",
    "デュダス": "Dudas",
    "ミュラド": "Murad",
    "シエーロ": "Siero",
    "パーリス": "Paris",
    "ターシュ": "Tarsh",
    "クリーフ": "Clief",
    "モンポー": "Monpo",
    "リーヴェ": "Rivei",
    "マガール": "Magar",
    "シーリャ": "Silia",
    "ザンドー": "Zando",
    "カナール": "Kanar",
    "ウルツア": "Ultua",
    "プーリィ": "Puryi",
    "クユーイ": "Kuyui",
    "メオーズ": "Meoze",
    "スーミュ": "Sumyu",
    "アプラト": "Aprat",
    "フレイア": "Freia",
    "モンツィ": "Monzi",
    "サーラン": "Saran",
    "ガットゥ": "Gattu",
    "グレース": "Grace",
    "エイナル": "Einar",
    "マロック": "Maroc",
    "ジャガイ": "Jagai",
    "ドラーク": "Drak",
    "アボット": "Abbot",
    "ピケット": "Piket",
    "ペインズ": "Penzu",
    "ボウマン": "Bowma",
    "カラマツ": "Larch",
    "プルッタ": "Pluta",
    "ビュブロ": "Byblo",
    "魔法使い": "mage",
    "ガッシュ": "Gash",
    "ネイビー": "navy",
    "あまいろ": "flax",
    "うすあい": "pale",
    "あみあみ": "mesh",
    "ポンコツ": "junk",
    "ペイジー": "Page",
    "エーリア": "Alia",
    "ティック": "Tick",
    "ヴェルト": "Velt",
    "セージィ": "Seji",
    "グウェン": "Gwen",
    "フーピー": "Fupi",
    "ホーポー": "Hopo",
    "タアテェ": "Tate",
    "ヴェルー": "Veru",
    "ウーボイ": "Uboi",
    "ガーディ": "Gadi",
    "イェーラ": "Yera",
    "ツーウィ": "Tsui",
    "ナーシュ": "Nash",
    "ウィット": "Uito",
    "オルヴァ": "Orva",
    "ジョエル": "Joel",
    "ミーナー": "Mina",
    "オットー": "Otto",
    "スパット": "Spat",
    "ヴァイン": "Vine",
    "アーミャ": "Amya",
    "エイベル": "Abel",
    "ヒュリー": "Huri",
    "スーディ": "Sudy",
    "ティーヤ": "Tiya",
    "イェード": "Yade",
    "ケーティ": "Katy",
    "ティジー": "Tiji",
    "ジャコウ": "Jako",
    "グレッグ": "Greg",
    "ギャリー": "Gary",
    "ハーティ": "Hati",
    "オオジャ": "Ooja",
    "サージュ": "Saju",
    "ヤーディ": "Yadi",
    "コーディ": "Cody",
    "チャップ": "Chap",
    "エフォー": "Epho",
    "ウッツァ": "Uzza",
    "ティニー": "Tiny",
    "ティヨン": "Tyon",
    "ディーエ": "Diei",
    "イツィオ": "Izio",
    "ラフィー": "Rafi",
    "アーリュ": "Aryu",
    "ヴィーサ": "Visa",
    "エイポン": "Apon",
    "ナーロー": "Naro",
    "ヘージャ": "Heja",
    "フェード": "Fedo",
    "ドゥーモ": "Dumo",
    "ヴェーロ": "Vero",
    "ヴィール": "Veer",
    "ピュリィ": "Puri",
    "ドゥドゥ": "Dudu",
    "エーデル": "Edel",
    "クルース": "Cruz",
    "フージュ": "Fuju",
    "フォーヴ": "Fove",
    "マキシー": "Maxi",
    "ビューガ": "Buga",
    "ヤーィヴ": "Yaiv",
    "キャーラ": "Cara",
    "ジューラ": "Jura",
    "オパール": "Opal",
    "フェール": "Feru",
    "アトゥイ": "Atui",
    "オーマス": "Omas",
    "ユージャ": "Yuja",
    "アールー": "Arue",
    "エゴール": "Egor",
    "アネさん": "sis",
    "アージュ": "Aju",
    "イーハー": "Eha",
    "ディーズ": "Diz",
    "ウィート": "Wit",
    "ワガハイ": "I",
    "でアール": "!",
    "レンタル": "rental",
    "ガラクタ": "junk",
    "リプレイ": "replay",
    "すばやさ": "agility",
    "きようさ": "deftness",
    "キャンプ": "camp",
    "アクセス": "access",
    "バッチリ": "perfectly",
    "サフィル": "Saphir",
    "デザイン": "design",
    "バリスン": "Barisun",
    "滅びの神": "God of Destruction",
    "えびせん": "Shrimp Snack",
    "イベント": "event",
    "木工職人": "Woodworker",
    "調理職人": "Cook",
    "ワクチン": "vaccine",
    "ゴンドラ": "gondola",
    "剣魔一族": "Spellsword Clan",
    "時の球根": "Time Bulb",
    "ジア燃石": "Diatite",
    "通話端末": "call terminal",
    "ティナナ": "Tinana",
    "ファリネ": "Farine",
    "ペネロペ": "Penelope",
    "時の化身": "Tockle",
    "クルッチ": "Ickle",
    "ヨッチ村": "Tickington",
    "ハルモス": "Harmos",
    "パウダー": "Powder",
    "ファラオ": "Pharaoh",
    "リーリナ": "Lilina",
    "パパーペ": "Papape",
    "ドレーク": "Drake",
    "神化の儀": "deification ritual",
    "プラコン": "Private Concierge",
    "シナリオ": "story",
    "裁縫部員": "Sewing Club member",
    "調理部員": "Cooking Club member",
    "木工部員": "Woodworking Club member",
    "ユーシャ": "Luminary",
    "オシッチ": "Tickle",
    "家具庭具": "furniture and garden furniture",
    "コーデ券": "glamour ticket",
    "さいほう": "sewing",
    "知の祝祭": "Wisdom Festival",
    "元の種族": "original race",
    "七不思議": "Seven Wonders",
    "輝晶効果": "Shine",
    "ヨッチ族": "Tockle",
    "超天道士": "Chosen One",
    "アンサー": "answer",
    "庭具倉庫": "garden storage",
    "レリーフ": "relief",
    "リューデ": "Ryude",
    "キヨクサ": "thrown",
    "ギョクサ": "throne",
    "ジンダタ": "Robbert Hoodlum",
    "アピール": "appeal",
    "心の輝き": "heart energy",
    "オルガン": "organ",
    "ゼェード": "Zeid",
    "サポート": "support",
    "真新しい": "brand new",
    "セラピア": "Serapia",
    "デルメゼ": "Delmeze",
    "ゼニアス": "Zeniath",
    "キタエル": "Trayne",
    "滅びの手": "Hand of Perdition",
    "護りの手": "Hand of Protection",
    "ベテラン": "veteran",
    "リサーチ": "research",
    "プリンス": "prince",
    "スィーテ": "Suitei",
    "ララモラ": "Laramora",
    "ポッケイ": "Pokkei",
    "シンリィ": "Shinry",
    "バルシラ": "Balsilla",
    "ジョスリ": "Josri",
    "ミケーレ": "Michele",
    "イウマド": "Iwmad",
    "カルアス": "Caluas",
    "ヤークト": "Yakuto",
    "ノーミア": "Normia",
    "ポップパ": "Poppupa",
    "サナーン": "Sanaan",
    "ボルタラ": "Voltara",
    "サユサラ": "Sayusara",
    "ピペッタ": "Pipetta",
    "フクロウ": "owl",
    "ゼネシア": "Zenethia",
    "ピッケル": "pickaxe",
    "ムニエカ": "Munieka",
    "ウォルド": "Angelfall",
    "メレちー": "Merry",
    "ジーくん": "Jee",
    "バルくん": "Asby",
    "トーくん": "Toh",
    "誓約の子": "children of the covenant",
    "聖守護者": "Sacred Sentinel",
    "友情の光": "Friendshine",
    "副素材A": "Sub-Material A",
    "やぐら": "fort",
    "大魔王": "Great Demon King",
    "天奏士": "divine musician",
    "プク女": "Pukulipo woman",
    "占い師": "fortune teller",
    "抜け道": "secret passage",
    "四術師": "Four Sorcerers",
    "物質系": "Material-type",
    "怪人系": "Humanoid-type",
    "会心率": "critical rate",
    "プク男": "Pukulipo man",
    "依頼書": "request form",
    "討伐隊": "strike force",
    "踊り神": "God of Dance",
    "震天王": "Heavenshaker",
    "みそぎ": "purification",
    "暴走率": "haywire rate",
    "造成地": "worksite",
    "大神殿": "Grand Temple",
    "念晶体": "telecrystal",
    "手水場": "water basin",
    "城下町": "Castle Town",
    "植物系": "Plant-type",
    "悪魔系": "Demon-type",
    "旅の扉": "teleportal",
    "六聖陣": "Six Saints",
    "あさぎ": "light blue",
    "スボバ": "Snowbattle",
    "魔創兵": "Evil Troop",
    "女教皇": "priestess",
    "そうび": "equipment",
    "天使長": "Archangel",
    "世界樹": "Yggdrasil",
    "候補者": "Candidate",
    "屋形船": "houseboat",
    "解放者": "liberator",
    "旅芸人": "minstrel",
    "遊び人": "gadabout",
    "魔術師": "magician",
    "あずき": "red bean",
    "あかね": "dark red",
    "初心者": "beginner",
    "フチチ": "Fuchichi",
    "ルチチ": "Ruchichi",
    "ツツハ": "Tsutsuha",
    "ツクシ": "Tsukushi",
    "ユチチ": "Yuchichi",
    "モモノ": "Sanguino",
    "ゴモラ": "Gomorrah",
    "チチカ": "Chichika",
    "ズチチ": "Zuchichi",
    "渡し守": "ferryman",
    "二の島": "2nd Isle",
    "三の島": "3rd Isle",
    "バトル": "battle",
    "マレレ": "Marelle",
    "レタス": "lettuce",
    "ヤチヨ": "Yachiyo",
    "ツヅリ": "Tsuduri",
    "シジマ": "Shijima",
    "ワシナ": "Washina",
    "シトリ": "Shitori",
    "シラベ": "Shirabe",
    "カゲツ": "Kagetsu",
    "ヤマシ": "Yamashi",
    "チカカ": "Chikaka",
    "ツタタ": "Tsutata",
    "チガヤ": "Chigaya",
    "ツバナ": "Tsubana",
    "ツムギ": "Tsumugi",
    "チグサ": "Chigusa",
    "モツゴ": "Motsugo",
    "ツグミ": "Tsugumi",
    "ヤツデ": "Yatsude",
    "チドリ": "Chidori",
    "ツナナ": "Tsunana",
    "コテツ": "Kotetsu",
    "チトセ": "Chitose",
    "レチカ": "Lechika",
    "ルギツ": "Rugitsu",
    "デジレ": "Desiree",
    "マゼラ": "Megella",
    "ナヅチ": "Nazuchi",
    "ナツリ": "Natsuri",
    "ツムム": "Tsumumu",
    "ムガチ": "Mugachi",
    "チケタ": "Chiketa",
    "チカリ": "Chikari",
    "クチバ": "Kuchiba",
    "トロぺ": "Toropei",
    "ドラン": "Sparkie",
    "シグレ": "Shigure",
    "シリリ": "Shiriri",
    "ヨシヤ": "Yoshiya",
    "ツユミ": "Tsuyumi",
    "シプレ": "Shipure",
    "チペラ": "Chipera",
    "ナトリ": "Natalie",
    "ころも": "clothes",
    "天星郷": "the Firmament",
    "げんま": "spirit",
    "踊り子": "dancer",
    "うける": "Accept",
    "チグリ": "Chigri",
    "コトル": "Kotoru",
    "ラミザ": "Ramiza",
    "ラセド": "Rasedo",
    "ハジカ": "Hajika",
    "ニニカ": "Ninika",
    "スギム": "Sugimu",
    "ゾデラ": "Zodera",
    "ナズナ": "Nazuna",
    "ミナナ": "Minana",
    "ガタラ": "Gatara",
    "キリカ": "Kirika",
    "ひつぎ": "coffin",
    "コーデ": "outfit",
    "ミモザ": "mimosa",
    "さくら": "cherry",
    "イカリ": "anchor",
    "大富豪": "Tycoon",
    "ヤヌビ": "Yanubi",
    "クラメ": "Kurame",
    "マリナ": "Marina",
    "ザナラ": "Zanara",
    "ララニ": "Rarani",
    "マトト": "Matoto",
    "サガラ": "Sagara",
    "トキワ": "Tokiwa",
    "ルブタ": "Rubuta",
    "ピリケ": "Pirike",
    "ペルピ": "Perupi",
    "クナナ": "Kunana",
    "ダズボ": "Dazubo",
    "ソロリ": "Sorori",
    "タラリ": "Tarari",
    "キサラ": "Kisara",
    "ミヤセ": "Miyase",
    "イツキ": "Itsuki",
    "カシー": "Cassie",
    "モニカ": "Monica",
    "ドモラ": "Domora",
    "ゴノザ": "Gonoza",
    "マキリ": "Makiri",
    "ハルト": "Haruto",
    "ポポロ": "Popolo",
    "パステ": "Pasute",
    "コロモ": "Koromo",
    "トベラ": "Tobera",
    "ナハギ": "Nahagi",
    "タマサ": "Tamasa",
    "ミヒラ": "Mihira",
    "ミヅキ": "Mizuki",
    "トノマ": "Tonoma",
    "キヨメ": "Kiyome",
    "イチル": "Ichiru",
    "カガト": "Kagato",
    "オシド": "Oshido",
    "キヅタ": "Kizuta",
    "ヨギサ": "Yogisa",
    "アシラ": "Ashira",
    "タタカ": "Tataka",
    "モノノ": "Monono",
    "ククラ": "Kukura",
    "セセラ": "Cecera",
    "ムルル": "Mururu",
    "シレレ": "Silere",
    "モココ": "Mokoko",
    "テテネ": "Tetene",
    "レミミ": "Remimi",
    "トトラ": "Totora",
    "ロロサ": "Lolosa",
    "テテマ": "Tetema",
    "スサナ": "Susana",
    "ルクバ": "Rukuba",
    "リミナ": "Limina",
    "ゼクバ": "Zekuba",
    "メメク": "Memeku",
    "ミズバ": "Mizuba",
    "スズミ": "Suzumi",
    "ソクラ": "Sokura",
    "カカラ": "Kakara",
    "ラポラ": "Lapora",
    "マニニ": "Manini",
    "ヨヒラ": "Yohira",
    "ペレナ": "Pelena",
    "イチハ": "Ichiha",
    "タルヒ": "Taruhi",
    "ユリネ": "Yurine",
    "ミズナ": "Mizuna",
    "カノコ": "Kanoko",
    "トモズ": "Tomozu",
    "ハヅヅ": "Hazuzu",
    "メメリ": "Memeri",
    "カフザ": "Kafuza",
    "ヒサメ": "Hisame",
    "マロナ": "Marona",
    "ヤブミ": "Yabumi",
    "カベラ": "Kabera",
    "セムラ": "Semula",
    "ガムリ": "Gamuri",
    "テラナ": "Telana",
    "ゲラド": "Gerado",
    "ガネス": "Ganess",
    "リブナ": "Libuna",
    "シリン": "Shirin",
    "クフラ": "Kufura",
    "ルミラ": "Lumira",
    "カニラ": "Kanira",
    "サマサ": "Samasa",
    "タラハ": "Taraha",
    "ピリロ": "Piriro",
    "カプナ": "Kapuna",
    "デネラ": "Denera",
    "メラネ": "Merane",
    "テテロ": "Tetero",
    "ポピリ": "Popiri",
    "タガヤ": "Tagaya",
    "トトニ": "Totoni",
    "ニトト": "Nitoto",
    "テナナ": "Tenana",
    "ハズキ": "Hazuki",
    "ドヨロ": "Doyoro",
    "ムカカ": "Mukaka",
    "コカブ": "Kokabu",
    "マルジ": "Maruji",
    "スバル": "Subaru",
    "マリド": "Malido",
    "フワロ": "Fuwaro",
    "マカロ": "Macaro",
    "ナクハ": "Nakuha",
    "コルナ": "Koruna",
    "シオネ": "Shione",
    "ホヅミ": "Hozumi",
    "ポプフ": "Popufu",
    "ポピピ": "Popipi",
    "パルナ": "Paruna",
    "ペルノ": "Peruno",
    "ニパナ": "Nipana",
    "ノポナ": "Nopona",
    "ポポリ": "Popori",
    "パパル": "Paparu",
    "ヌツィ": "Newtsy",
    "ミカモ": "Mikamo",
    "キラリ": "Kirari",
    "サラサ": "Sarasa",
    "タバネ": "Tabane",
    "ベルタ": "Bertha",
    "パパラ": "Papala",
    "キルル": "Kilulu",
    "ラクト": "Lakuto",
    "ゾクラ": "Zokura",
    "クロク": "Kuroku",
    "ポレロ": "Polero",
    "サシモ": "Sashim",
    "パタタ": "Patata",
    "ロクロ": "Rokuro",
    "ミペカ": "Mipeka",
    "コレス": "Koresu",
    "ハピピ": "Hapipi",
    "ピタリ": "Pitary",
    "ガラハ": "Galaha",
    "ヤシム": "Yashim",
    "ミカゲ": "Mikage",
    "ペルル": "Peruru",
    "トルマ": "Toruma",
    "マカラ": "Makara",
    "バビロ": "Babilo",
    "ロココ": "Rococo",
    "マトリ": "Matori",
    "クリロ": "Kurilo",
    "カタナ": "Katana",
    "ダガマ": "Dagama",
    "パララ": "Parala",
    "ズムニ": "Zumuni",
    "ビナヤ": "Vinaya",
    "ネフラ": "Nefura",
    "トロメ": "Torome",
    "ベスコ": "Sheeko",
    "ベスナ": "Sheena",
    "ベスノ": "Sheeno",
    "ベスミ": "Sheemi",
    "ハラリ": "Halali",
    "ブロド": "Burodo",
    "メドリ": "Medori",
    "カルタ": "Karuta",
    "トレド": "Toledo",
    "バサキ": "Basaki",
    "クヨチ": "Kyochi",
    "ニニモ": "Ninimo",
    "カガミ": "Kagami",
    "ササミ": "Sasari",
    "ナギモ": "Nagimo",
    "ソマリ": "Somali",
    "レレノ": "Releno",
    "サテテ": "Satete",
    "ガララ": "Galara",
    "ダクル": "Duckle",
    "スメメ": "Sumeme",
    "タレレ": "Tarere",
    "ッティ": "Thatty",
    "ハヤテ": "Hayate",
    "カラリ": "Kalari",
    "レシア": "Reshia",
    "モハビ": "Mohabi",
    "ルミネ": "Lumine",
    "スミカ": "Sumika",
    "メゾナ": "Mezona",
    "コポコ": "Copoco",
    "ストト": "Sutoto",
    "ミズメ": "Mizume",
    "グノバ": "Gunova",
    "カズラ": "Kazula",
    "ザニフ": "Zanifu",
    "ダリダ": "Dalida",
    "リコラ": "Ricola",
    "レビデ": "Rebide",
    "ゾレト": "Zoleto",
    "ナズマ": "Nazuma",
    "ポペナ": "Popena",
    "レロネ": "Lelone",
    "ミノノ": "Minono",
    "ナナロ": "Nanaro",
    "ヒナタ": "Hinata",
    "ヨギリ": "Yogiri",
    "キノメ": "Kinome",
    "モララ": "Morara",
    "プフル": "Puffle",
    "テラン": "Terran",
    "タブレ": "Tabure",
    "トナナ": "Tonana",
    "サララ": "Salara",
    "ガリス": "Garris",
    "プペル": "Puperu",
    "ヨグナ": "Yoguna",
    "ネウェ": "Neiwei",
    "レタラ": "Retara",
    "ナミホ": "Namiho",
    "モコロ": "Mokoro",
    "ササラ": "Sasara",
    "ヤママ": "Yamama",
    "カカナ": "Kakana",
    "トトポ": "Totopo",
    "タタラ": "Tatara",
    "バナパ": "Banapa",
    "ガガド": "Gagado",
    "ホメメ": "Homeme",
    "ヒソカ": "Hisoka",
    "シカン": "Shikan",
    "マリハ": "Mariha",
    "カワラ": "Kawara",
    "カシヲ": "Kashio",
    "カリヤ": "Kariya",
    "サクラ": "Sakura",
    "カカフ": "Kakafu",
    "ホホナ": "Hohona",
    "ヘレナ": "Helena",
    "マノロ": "Manoro",
    "マリサ": "Marisa",
    "ヤヤク": "Yayaku",
    "ユネネ": "Yunene",
    "コキヒ": "Kokihi",
    "アラネ": "Aranei",
    "ジヌガ": "Jinuga",
    "ヨプリ": "Yopuri",
    "リピコ": "Lipico",
    "イダテ": "Idatei",
    "テルペ": "Terupe",
    "ミツカ": "Mitska",
    "ユムム": "Yumumu",
    "ヤキル": "Yakiru",
    "ハネギ": "Hanegi",
    "マギー": "Maggie",
    "セリナ": "Serina",
    "カリマ": "Karima",
    "ヤココ": "Yakoko",
    "キセラ": "Kisera",
    "ホワラ": "Howara",
    "レオニ": "Leonie",
    "トボラ": "Tobora",
    "ハルザ": "Haruza",
    "バグタ": "Baguta",
    "ご主人": "master",
    "とくぎ": "skill",
    "コホン": "cough",
    "ゼドラ": "Zedra",
    "ヨロイ": "armor",
    "ジダン": "Jidan",
    "パクレ": "Pakul",
    "ピィピ": "Pippi",
    "ヘルガ": "Helga",
    "カンナ": "Kanna",
    "ユリア": "Julia",
    "シタル": "Sitar",
    "ゲゾラ": "Gezra",
    "ラウラ": "Laura",
    "ミーミ": "Meemi",
    "ラゴス": "Lagos",
    "メナー": "Menna",
    "ヌブロ": "Nubro",
    "三闘士": "Triad",
    "ホルタ": "Holta",
    "セレド": "Celed",
    "さんご": "coral",
    "パール": "pearl",
    "ひとみ": "pupil",
    "コホッ": "cough",
    "シュラ": "Shura",
    "しぐさ": "emote",
    "ガラン": "Galan",
    "ヤナギ": "Yangi",
    "メメル": "Memel",
    "ススラ": "Slurp",
    "タタン": "Tatan",
    "ノギク": "Nogik",
    "アマト": "Amato",
    "モエギ": "Moegi",
    "アカネ": "Akane",
    "プッチ": "Pucci",
    "マーユ": "Maayu",
    "ザラン": "Zaran",
    "ボスタ": "Bosta",
    "グッタ": "Getta",
    "トリン": "Torin",
    "ガーゴ": "Gargo",
    "グイブ": "Guive",
    "ポコア": "Pokoa",
    "イヨリ": "Iyori",
    "モカム": "Mokam",
    "アサギ": "Asagi",
    "シーナ": "Shina",
    "ユーフ": "Yuffe",
    "ルンタ": "Runta",
    "クック": "Cooke",
    "ナディ": "Nadie",
    "リュリ": "Lulie",
    "セラム": "Salem",
    "ドギス": "Dogis",
    "ヴァン": "Vanne",
    "デドダ": "Dedoa",
    "グイド": "Guido",
    "シェラ": "Shera",
    "サリィ": "Sally",
    "ケシャ": "Kesha",
    "シュパ": "Shupa",
    "グスガ": "Gusga",
    "ゲバン": "Geban",
    "ノクタ": "Nocta",
    "ピッツ": "Pitts",
    "ヤポル": "Yapor",
    "ユピン": "Yupin",
    "プルア": "Purua",
    "トロペ": "Trope",
    "アコヤ": "Akoya",
    "ヤスナ": "Yasna",
    "カスリ": "Kasri",
    "ウメノ": "Umeno",
    "ウコギ": "Ukogi",
    "イグサ": "Igusa",
    "コウヤ": "Kouya",
    "トリリ": "Trili",
    "ルルア": "Lulua",
    "ムムセ": "Mumse",
    "タブロ": "Tablo",
    "タタイ": "Tatai",
    "ガツェ": "Gashe",
    "ムウリ": "Muuri",
    "フフイ": "Fufui",
    "アココ": "Akoko",
    "ユユン": "Yuyun",
    "ゴンボ": "Gonbo",
    "アセビ": "Asebi",
    "ダンケ": "Danke",
    "ペルレ": "Perle",
    "ボリス": "Boris",
    "ポロオ": "Poroo",
    "ヨイジ": "Yoiji",
    "ロクア": "Rokua",
    "ソテツ": "Sotsu",
    "ルンネ": "Lunne",
    "パジル": "Basil",
    "サユル": "Sayul",
    "レンカ": "Renka",
    "ペトラ": "Petra",
    "クニャ": "Kunya",
    "トイム": "Toimu",
    "アケビ": "Akebi",
    "キュラ": "Kyura",
    "レリー": "Lerry",
    "ハラル": "Halar",
    "チョフ": "Chofu",
    "パルノ": "Parno",
    "モクア": "Mokua",
    "タリア": "Taria",
    "リゲス": "Rigez",
    "エリス": "Ellis",
    "ユメル": "Yumel",
    "ショル": "Shoru",
    "ブラト": "Burat",
    "カノス": "Kanos",
    "リゲル": "Rigel",
    "ハカム": "Hakam",
    "アサル": "Asaru",
    "トルテ": "Torte",
    "ミネア": "Meena",
    "ガガロ": "Gagar",
    "グルビ": "Gulbi",
    "ナナイ": "Nanai",
    "ツィネ": "Zinei",
    "アマネ": "Amane",
    "シュタ": "Shuta",
    "ピラル": "Piral",
    "ゴラル": "Goral",
    "ギリン": "Girin",
    "イサラ": "Isara",
    "ルピア": "Lipia",
    "ホマズ": "Homas",
    "イドラ": "Idola",
    "カイラ": "Caira",
    "ミリヤ": "Miria",
    "オトワ": "Otowa",
    "モルン": "Morun",
    "ギッソ": "Gisso",
    "チュノ": "Chuno",
    "リーニ": "Rinne",
    "ケリー": "Kelly",
    "セグル": "Segul",
    "セネル": "Senel",
    "ヘーナ": "Henna",
    "ギルロ": "Gillo",
    "ケープ": "Keppu",
    "シュン": "Shuna",
    "ムウナ": "Moona",
    "ケイブ": "Keibu",
    "デネブ": "Deneb",
    "ホンギ": "Hongi",
    "シラー": "Syrah",
    "ウヌク": "Unuku",
    "ラマン": "Raman",
    "ラッカ": "Rakka",
    "ウルメ": "Urume",
    "パフィ": "Puffy",
    "ロッシ": "Rossi",
    "シトロ": "Citro",
    "バルド": "Baldo",
    "ショス": "Shose",
    "バイグ": "Baigu",
    "ショコ": "Shoko",
    "ダラス": "Dalas",
    "ギルダ": "Gilda",
    "カレン": "Karen",
    "ネリー": "Nelly",
    "チュナ": "Chuna",
    "アザミ": "Azami",
    "グリフ": "Glyph",
    "プラヌ": "Planu",
    "ポーツ": "Ports",
    "パホン": "Pahon",
    "ピフィ": "Piffy",
    "ポフェ": "Poffy",
    "ラバン": "Raban",
    "メリア": "Melia",
    "ワバン": "Waban",
    "ルバン": "Ruban",
    "クバン": "Kuban",
    "ポリィ": "Polly",
    "リーリ": "Leely",
    "イナバ": "Inaba",
    "カリン": "Karin",
    "ガルゴ": "Galgo",
    "ポッケ": "Pokke",
    "パピィ": "Pappy",
    "クルリ": "Kulry",
    "ネオル": "Neoru",
    "トルギ": "Tolgi",
    "クラギ": "Kragi",
    "プッカ": "Pucca",
    "ソルテ": "Solte",
    "ダジン": "Dazin",
    "ゼリオ": "Zelio",
    "ロッカ": "Lokka",
    "ホミィ": "Healy",
    "ガダン": "Gadan",
    "スズネ": "Suzun",
    "ロチャ": "Rocha",
    "アマハ": "Amaha",
    "モンテ": "Monte",
    "パオラ": "Paola",
    "ビリー": "Billy",
    "ラキー": "Rakky",
    "ユウユ": "Yuuyu",
    "ルンル": "Runru",
    "セレプ": "Celep",
    "トニア": "Tonia",
    "トマル": "Tomal",
    "イグニ": "Iguni",
    "ナルギ": "Nargi",
    "エナギ": "Enagi",
    "メリュ": "Meryu",
    "イゾラ": "Izola",
    "イプル": "Ipuru",
    "ルスパ": "Luspa",
    "ペリド": "Perid",
    "カルセ": "Calse",
    "ジェダ": "Jedah",
    "ワーレ": "Warei",
    "ペイプ": "Peipu",
    "ミルネ": "Milne",
    "バンス": "Vance",
    "テトリ": "Tetri",
    "メトラ": "Metra",
    "マヌヌ": "Manun",
    "ムクゲ": "Mukuge",
    "ユシエ": "Yushi",
    "クラロ": "Claro",
    "タータ": "Tarta",
    "ヤッフ": "Yaffu",
    "ポタン": "Potan",
    "イルギ": "Irugi",
    "グルゾ": "Gulzo",
    "カブラ": "Kabra",
    "セレテ": "Seret",
    "ロンブ": "Lonbu",
    "ヨルカ": "Yorka",
    "ワトス": "Watos",
    "コルベ": "Kolbe",
    "ベスン": "Besun",
    "ラッピ": "Rappi",
    "ウナス": "Unasu",
    "トーレ": "Torre",
    "レジア": "Regia",
    "ヘリン": "Herin",
    "ボラス": "Bolas",
    "エリカ": "Erica",
    "ノンナ": "Nonna",
    "アカリ": "Akari",
    "ムニュ": "Munyu",
    "ネウズ": "Neuzu",
    "ビレー": "Belay",
    "コルギ": "Corgi",
    "サラム": "Salam",
    "バレイ": "Barei",
    "サンサ": "Sansa",
    "ネムド": "Nemdo",
    "モギィ": "Moggy",
    "スドラ": "Sudra",
    "レトト": "Letto",
    "リリン": "Lilin",
    "パカル": "Pacal",
    "クレプ": "Crepe",
    "ルヒオ": "Ruhio",
    "モルド": "Mordo",
    "ムヤル": "Muyal",
    "テッカ": "Tekka",
    "ルード": "Luudo",
    "タンタ": "Tanta",
    "ビスカ": "Bisca",
    "ゼラン": "Zelan",
    "ブレダ": "Breda",
    "リンネ": "Linne",
    "ベンタ": "Venta",
    "ミミラ": "Mimil",
    "プラワ": "Prawa",
    "アママ": "Amama",
    "サナム": "Sanam",
    "バヌス": "Banus",
    "ピッケ": "Pikke",
    "レジエ": "Regie",
    "シジュ": "Shiju",
    "ガブラ": "Gabra",
    "プゴル": "Pugol",
    "バメア": "Vamea",
    "ロッガ": "Logga",
    "モルザ": "Morza",
    "ソリヤ": "Solya",
    "マディ": "Maddy",
    "マータ": "Marta",
    "ガルド": "Gardo",
    "ボクス": "Bokus",
    "ピラト": "Pilat",
    "ドンザ": "Donza",
    "ゴーシ": "Goshi",
    "レベレ": "Rebre",
    "ゴボン": "Gobon",
    "テーレ": "Terre",
    "アカカ": "Akaka",
    "リラエ": "Lilae",
    "オリリ": "Oriri",
    "ジェマ": "Gemma",
    "リンマ": "Linma",
    "プロン": "Puron",
    "ウラカ": "Uraka",
    "タウノ": "Tauno",
    "パフタ": "Pufta",
    "モヌス": "Monus",
    "カンザ": "Kanza",
    "ユゴオ": "Yugoo",
    "スット": "Sutto",
    "パサル": "Pasal",
    "キュル": "Kyuru",
    "センナ": "Senna",
    "ノロン": "Nolon",
    "スプヤ": "Spuya",
    "ギモフ": "Gimov",
    "ナリア": "Naria",
    "ワッタ": "Watta",
    "ヤウラ": "Yaura",
    "ガスタ": "Gasta",
    "ゲルン": "Gerun",
    "ニドン": "Nidon",
    "ニイペ": "Niipe",
    "ゴンゾ": "Gonzo",
    "ググル": "Gugur",
    "テテオ": "Teteo",
    "チェラ": "Chera",
    "マヨイ": "Mayoi",
    "ポルト": "Porto",
    "オペラ": "Opera",
    "パッチ": "Patch",
    "プリオ": "Purio",
    "プーペ": "Poupe",
    "アノカ": "Anoka",
    "イサリ": "Isari",
    "イレス": "Iless",
    "ガニャ": "Ganya",
    "ポッチ": "Potch",
    "セピア": "Sepia",
    "ピペル": "Pipel",
    "パプナ": "Papna",
    "ピツァ": "Pizza",
    "スピカ": "Spika",
    "エミヤ": "Emiya",
    "アキラ": "Akira",
    "ズショ": "Zusho",
    "ラデン": "Raden",
    "ウキヨ": "Ukiyo",
    "ナンタ": "Nanta",
    "イヒラ": "Ihira",
    "アナナ": "Anana",
    "ロシャ": "Rosha",
    "ガリャ": "Garya",
    "ラドワ": "Radwa",
    "ゼルル": "Zerul",
    "リリル": "Lilyl",
    "ドドル": "Dodol",
    "ホホル": "Hohol",
    "リリア": "Lilia",
    "ブブラ": "Bubra",
    "バァス": "Baasu",
    "ステフ": "Steph",
    "リモン": "Rimon",
    "バスラ": "Basra",
    "カンラ": "Kanra",
    "ポンム": "Pomme",
    "ケーネ": "Kenei",
    "ザンバ": "Zamba",
    "ラビィ": "Rabbi",
    "ポンタ": "Ponta",
    "アロロ": "Aroro",
    "マニー": "Manny",
    "キンナ": "Kinna",
    "カチャ": "Kacha",
    "リリイ": "Lilly",
    "ギルバ": "Gilba",
    "ハッケ": "Hakke",
    "トトン": "Toton",
    "バンギ": "Bangi",
    "シェリ": "Sheri",
    "コダマ": "Kodam",
    "ロニー": "Ronny",
    "ボッタ": "Botta",
    "ガット": "Gatto",
    "アププ": "Apupu",
    "マチェ": "Mache",
    "ガンボ": "Gumbo",
    "ロウダ": "Rouda",
    "パルカ": "Parka",
    "ハロン": "Haron",
    "チュダ": "Chuda",
    "マズル": "Mazur",
    "メルカ": "Merca",
    "コウロ": "Kouro",
    "ベント": "Bento",
    "コチョ": "Kocho",
    "アガタ": "Agata",
    "ボチボ": "Bochi",
    "マッカ": "Macca",
    "デンナ": "Denna",
    "ケチャ": "Kecha",
    "ソイル": "Soyle",
    "ゴダン": "Godan",
    "プポル": "Pupol",
    "まぅろ": "Mauro",
    "ウェナ": "Wena",
    "グレン": "Glen",
    "どうぐ": "item",
    "メルー": "Meru",
    "トール": "Thor",
    "ダイム": "Dyme",
    "トレダ": "Tred",
    "リリィ": "Lily",
    "ヨンゲ": "Yong",
    "グリエ": "Grie",
    "ゲルト": "Gert",
    "レーン": "Rane",
    "ムスト": "Morst",
    "ウルタ": "Ulta",
    "ピンク": "pink",
    "ブルー": "blue",
    "クレイ": "clay",
    "ミント": "mint",
    "コルク": "cork",
    "ルーラ": "Zoom",
    "ムーン": "Moon",
    "ロジェ": "Roje",
    "リーゼ": "Lyse",
    "ミュル": "Mule",
    "バート": "Bart",
    "ワイズ": "Wyze",
    "ガトゥ": "Gatu",
    "ヴァド": "Vado",
    "フュン": "Hyun",
    "オルダ": "Orda",
    "キーン": "Keen",
    "ギュン": "Gyun",
    "クシュ": "Kush",
    "レアン": "Rean",
    "ノーム": "Nomu",
    "イオリ": "Iori",
    "オボロ": "Obor",
    "ルオプ": "Luop",
    "クルム": "Kulm",
    "ハーリ": "Hari",
    "バアス": "Baas",
    "サフィ": "Safi",
    "セベー": "Sebe",
    "ラーク": "Raku",
    "プルム": "Plum",
    "コアム": "Coam",
    "アオノ": "Aono",
    "ラプパ": "Lapa",
    "アアテ": "Aate",
    "タヴィ": "Tavi",
    "アンニ": "Anni",
    "コルツ": "Colz",
    "ラーニ": "Lani",
    "バーノ": "Bano",
    "アルラ": "Arla",
    "ジーナ": "Gina",
    "ブラン": "Bran",
    "デイブ": "Dave",
    "ピート": "Pete",
    "ギティ": "Giti",
    "ローネ": "Rone",
    "ニーノ": "Nino",
    "チェド": "Ched",
    "ユアン": "Yuan",
    "ルルー": "Ruru",
    "レーナ": "Rena",
    "シーニ": "Sini",
    "ダッツ": "Dats",
    "シディ": "Sidi",
    "ブール": "Buru",
    "モティ": "Moti",
    "チャド": "Chad",
    "エニフ": "Enif",
    "シェム": "Shem",
    "ディラ": "Dira",
    "ルチル": "Ruci",
    "ニョイ": "Nyoi",
    "エッダ": "Edda",
    "ジラー": "Jira",
    "アイミ": "Aimi",
    "アハド": "Ahad",
    "ルーブ": "Rube",
    "アルゴ": "Argo",
    "ウーゾ": "Ouzo",
    "オムザ": "Omza",
    "クオン": "Kuon",
    "レイド": "raid",
    "ハイム": "Heim",
    "ヌーガ": "Nuga",
    "クティ": "Kuti",
    "ヒュナ": "Huna",
    "ドリー": "Dory",
    "エバン": "Eban",
    "ドギー": "Dogi",
    "オリギ": "Olgi",
    "ウエギ": "Uegi",
    "ミリィ": "Miry",
    "テウス": "Teus",
    "レーミ": "Remi",
    "ペラリ": "Pera",
    "ギリー": "Gill",
    "イリー": "Illy",
    "トーン": "Tone",
    "ネジュ": "Neju",
    "リィト": "Lito",
    "トロン": "Tron",
    "チアア": "Chia",
    "ガウェ": "Gawe",
    "ゾイン": "Zoin",
    "ユーラ": "Yula",
    "クヴァ": "Kuva",
    "グナー": "Guna",
    "ミード": "Meed",
    "ルゴー": "Lugo",
    "ペッス": "Pess",
    "ミエル": "Miel",
    "ルスク": "Rusk",
    "アトリ": "Ally",
    "ミーヌ": "Minu",
    "ククス": "Kook",
    "タリス": "Tals",
    "コイズ": "Koiz",
    "ラゴウ": "Lago",
    "ラヴィ": "Ravi",
    "ベスエ": "Shea",
    "カーク": "Kirk",
    "ジュテ": "Jute",
    "ティロ": "Tiro",
    "ヘール": "Hale",
    "ソール": "Saul",
    "エイラ": "Eira",
    "ルギー": "Rugi",
    "メアル": "Mare",
    "バッヅ": "Badz",
    "ベディ": "Bedi",
    "ティゴ": "Tigo",
    "アチャ": "Acha",
    "ホルト": "Holt",
    "ザップ": "Zapp",
    "ウリル": "Uril",
    "ヴィラ": "Vira",
    "カーサ": "Casa",
    "キダチ": "Kida",
    "パオス": "Paos",
    "レビィ": "Rebi",
    "アロト": "Arot",
    "ザーク": "Zark",
    "スコル": "Scor",
    "クロエ": "Kroe",
    "ジーヌ": "Gene",
    "グォン": "Guon",
    "ザール": "Zarr",
    "ヨッチ": "Yoch",
    "イグマ": "Igma",
    "ホーロ": "Horo",
    "ベビー": "baby",
    "アウダ": "Auda",
    "ジーン": "Jean",
    "立て札": "sign",
    "アルパ": "Alpa",
    "ポンク": "Ponk",
    "イケウ": "Ikeu",
    "クルイ": "Krui",
    "イウカ": "Iuka",
    "アニク": "Anik",
    "ブイイ": "Buii",
    "フファ": "Fufa",
    "ヅィラ": "Zira",
    "アッカ": "Akka",
    "ルース": "Ruth",
    "トージ": "Toji",
    "ヌルー": "Nuru",
    "メロー": "Mero",
    "ナーズ": "Nazu",
    "ライル": "Lyle",
    "エマル": "Emal",
    "アンナ": "Anna",
    "オルグ": "Orgu",
    "イイト": "Eito",
    "プーレ": "Pure",
    "アーリ": "Arri",
    "オルカ": "Orca",
    "ティモ": "Timo",
    "インゴ": "Ingo",
    "ホルプ": "Holp",
    "マフー": "Mafu",
    "ビーン": "Bean",
    "バルフ": "Balf",
    "ユディ": "Yudi",
    "めんこ": "pog",
    "ぶくろ": "bag",
    "アンタ": "you",
    "キミぃ": "you",
    "フウキ": "SCC",
    "ぼうし": "hat",
    "ヴィク": "Vic",
    "ディア": "Dia",
    "アルプ": "Alp",
    "トゥグ": "Tug",
    "アーラ": "Ala",
    "ゼッド": "Zed",
    "トック": "Tok",
    "ミュウ": "Miu",
    "ハッグ": "Hag",
    "ビット": "Bit",
    "エスク": "Esk",
    "ニクス": "Nix",
    "エーヴ": "Ave",
    "オリー": "Ori",
    "オミー": "Omi",
    "トィン": "Tin",
    "ラーイ": "Rai",
    "イシュ": "Ish",
    "スオウ": "Suo",
    "フィア": "Fia",
    "ティア": "Tia",
    "タイズ": "Taz",
    "ダウラ": "Dar",
    "ツキヨ": "Tsu",
    "ディグ": "Dig",
    "アース": "Asu",
    "ショー": "Sho",
    "ユーイ": "Yui",
    "フェア": "Fea",
    "イェン": "Yen",
    "エール": "Ale",
    "ルーア": "Lua",
    "イーハ": "Iha",
    "ケヤキ": "Elm",
    "アタイ": "me",
    "オッド": "Od",
    "エドー": "Ed",
    "タマ！": "!",
    "オイラ": "I",
    "アナタ": "you",
    "おもさ": "weight",
    "プレイ": "play",
    "メイヴ": "Meiv",
    "シドー": "Malroth",
    "写真機": "photo machine",
    "名声値": "Fame Points",
    "ルーベ": "Rubay",
    "デイン": "Zap",
    "ポート": "Port",
    "ジョス": "Joss",
    "グッス": "Guss",
    "ハクヒ": "Hakuhi",
    "ペペプ": "Pepepu",
    "ツイナ": "Tuina",
    "セスタ": "Cesta",
    "光の河": "River of Light",
    "起動石": "Starting Stone",
    "ラベル": "label",
    "輝晶獣": "Pyrobeast",
    "湯の花": "spring minerals",
    "ダーマ": "Alltrades",
    "アジト": "hideout",
    "烈火掌": "Fiery Palm",
    "水撃砲": "Water Gun",
    "念晶鏡": "Telecrystal Mirror",
    "氷毒弾": "toxic ice shard",
    "爆破弾": "bombshell",
    "光滅弾": "purifying pellet",
    "ポポコ": "Popoko",
    "ネーガ": "Nega",
    "魔瘴石": "Miasmite",
    "トニー": "Tony",
    "ベニー": "Benny",
    "プポペ": "Pupope",
    "メアリ": "Mary",
    "ゲノス": "Genos",
    "撃破玉": "Attack Orb",
    "援軍玉": "Reinforcement Orb",
    "裁縫部": "Sewing Club",
    "調理部": "Cooking Club",
    "木工部": "Woodworking Club",
    "段位戦": "Ranked Match",
    "水そう": "aquarium",
    "魔闘士": "magic warrior",
    "白き者": "White One",
    "緑の者": "Green Thumb",
    "第３刻": "Third Epoch",
    "第４刻": "Fourth Epoch",
    "第５刻": "Fifth Epoch",
    "第７刻": "Seventh Epoch",
    "ヒズミ": "distortion",
    "想望華": "Yearning Flower",
    "岩屋前": "Grotto",
    "マルゴ": "Margo",
    "ホズキ": "Hozuki",
    "リズク": "Rizk",
    "ラティ": "Rati",
    "ロビサ": "Lovisa",
    "オドモ": "Odomo",
    "セララ": "Serara",
    "ナテラ": "Natera",
    "オレイ": "Olay",
    "ロミナ": "Romina",
    "シロギ": "Shirogi",
    "ミアナ": "Miana",
    "リュバ": "Lyuba",
    "大祭壇": "The Great Altar",
    "竜術士": "dragomancer",
    "メネト": "Menet",
    "バカン": "Bakan",
    "ダリピ": "Drippy",
    "親密度": "bond",
    "勇士": "brave warrior",
    "魔瘴": "demon miasma",
    "天声": "divine voice",
    "無声": "silent voice",
    "虫系": "Insect-type",
    "節制": "temperance",
    "獣系": "Beast-type",
    "水系": "Water-type",
    "王都": "Royal City",
    "冥王": "Netherlord",
    "審判": "judgement",
    "鳥系": "Bird-type",
    "仲間": "companion",
    "陽衆": "Yang Clan",
    "聖域": "sanctuary",
    "職業": "vocation",
    "種族": "races",
    "正義": "justice",
    "皇帝": "emperor",
    "女帝": "empress",
    "修羅": "carnage",
    "海賊": "pirate",
    "死神": "reaper",
    "罪人": "sinner",
    "隠者": "hermit",
    "霊子": "spirit",
    "旦那": "master",
    "特技": "skill",
    "呪文": "spell",
    "恋人": "lover",
    "悪魔": "demon",
    "クチ": "mouth",
    "悪神": "fiend",
    "試練": "trial",
    "アト": "marks",
    "守護": "protection",
    "丘陵": "hills",
    "つぼ": "vase",
    "戦車": "chariot",
    "教皇": "pope",
    "愚者": "fool",
    "盟友": "ally",
    "カオ": "face",
    "ボケ": "Pratfall",
    "ワギ": "Wagi",
    "キミ": "you",
    "絵馬": "ema",
    "オデ": "I",
    "村長": "chief",
    "魔物": "monster",
    "主人": "master",
    "短冊": "paper strip",
    "印章": "stamp",
    "神具": "divine artifact",
    "閃手": "athlight",
    "庭具": "garden furniture",
    "家具": "furniture",
    "会心": "critical",
    "魔獣": "demon beast",
    "極致": "perfection",
    "写真": "photo",
    "封筒": "envelope",
    "創失": "unmaking",
    "ロナ": "Rona",
    "黒槍": "Black Spear",
    "館": "mansion",
    "楯": "shield",
    "塔": "tower",
    "筒": "tube",
    "扇": "fan",
    "弓": "bow",
    "筆": "pen",
    "墓": "tomb",
    "球": "ball",
    "盾": "shield",
    "鎌": "scythe",
    "駅": "train station",
    "泉": "fountain",
    "深部": "depths",
    "最深部": "depths",
    "魔王": "Demon King",
    "賢者": "sage",
    "巫女": "maiden",
    "成功": "success",
    "モテモテ": "popular",
    "石碑": "stone monument",
    "階段": "stairs",
    "聖堂": "shrine",
    "中央": "center",
    "階段": "stairs",
    "少年": "boy",
    "売店": "shop",
    "教会": "church",
    "自宅": "home",
    "少年": "boy",
    "お箸": "chopsticks",
    "書庫": "archives",
    "ツボ": "pot",
    "楽器": "instrument",
    "屋内": "indoors",
    "校庭": "campus",
    "座礼": "sit and bow",
    "格闘": "bare hands",
    "村人": "villager",
    "花園前": "flower garden",
    "花園": "flower garden",
    "官舎": "residence",
    "南口": "south exit",
    "西翼": "west wing",
    "菜園": "vegetable garden",
    "金庫": "safe",
    "御殿": "palace",
    "車掌": "conductor",
    "芯層": "core",
    "神獣": "divine beast",
    "神像": "idol",
    "兄弟": "brothers",
    "城壁": "castle walls",
    "大剣": "greatsword",
    "居室": "living room",
    "地上": "surface",
    "墓場": "graveyard",
    "倉庫": "warehouse",
    "本黄": "yellow book",
    "本紫": "purple book",
    "物置": "storage room",
    "妄想": "swoon",
    "灯籠": "lantern",
    "厨房": "kitchen",
    "船内": "ship",
    "宝箱": "treasure chest",
    "水門": "water gate",
    "救護": "relief",
    "教卓": "teacher's desk",
    "食堂": "dining room",
    "輝晶獣": "Crystalbeast",
    "機関部": "engine",
    "浴室": "bathroom",
    "広場": "plaza",
    "上階": "upper floor",
    "下階": "lower floor",
    "本緑": "green book",
    "木箱": "crate",
    "電池": "battery",
    "廃屋": "abandoned house",
    "カギ": "key",
    "鉱山": "mine",
    "ねじ": "screw",
    "甲板": "deck",
    "市場": "market",
    "外側": "exterior",
    "深淵": "ravine",
    "小島": "islet",
    "本赤": "red book",
    "薄明": "twilight",
    "泥沼": "bog",
    "勇者": "Hero",
    "店内": "shop interior",
    "氷床": "ice sheet",
    "中庭": "courtyard",
    "駅前": "train station",
    "宿屋": "inn",
    "雪山": "snowy mountain",
    "玄関": "foyer",
    "通路": "passage",
    "寝室": "bedroom",
    "呪詛": "curse",
    "風車": "windmill",
    "本黄": "yellow book",
    "オノ": "axe",
    "中層": "middle-level",
    "神官": "priest",
    "海岸": "coast",
    "客室": "guest room",
    "公園": "park",
    "海岸": "coast",
    "岩群": "rockpile",
    "講堂": "auditorium",
    "金箱": "gold box",
    "重塔": "pagoda",
    "霊堂": "mausoleum",
    "灯台": "lighthouse",
    "控室": "waiting room",
    "本青": "blue book",
    "南門": "south gate",
    "輪廻": "reborn",
    "屋上": "roof",
    "石版": "tablet",
    "表層": "surface",
    "山頂": "summit",
    "花園": "flower garden",
    "広間": "hall",
    "人魂": "soul",
    "ツメ": "claws",
    "庭園": "garden",
    "大砲": "cannon",
    "深層": "depths",
    "沼大": "large swamp",
    "竜族": "Nadravian",
    "牢屋": "jail",
    "井戸": "well",
    "落日": "sunset",
    "東翼": "east wing",
    "茶室": "tea room",
    "高峰": "peak",
    "回復": "recovery",
    "亀裂": "crack",
    "祭壇": "altar",
    "人間": "human",
    "雪女": "snow woman",
    "神殿": "temple",
    "闇夜": "night",
    "短剣": "dagger",
    "霊廟": "tomb",
    "小舟": "small boat",
    "内側": "interior",
    "沼小": "small swamp",
    "塔前": "tower",
    "墓地": "graveyard",
    "ムチ": "whip",
    "図書室": "library",
    "武闘家": "martial artist",
    "魔剣士": "demon swordsman",
    "レンジャー": "ranger",
    "わらう": "laugh",
    "デスマスター": "death master",
    "バトルマスター": "battlemaster",
    "両手剣": "greatsword",
    "片手剣": "sword",
    "ギルド": "Guild",
    "ガンバライオン": "Ganbalion",
    "ポルるん": "Portie",
    "マギエル": "Magiel",
    "ゼニート": "Zenit",
    "リムネル": "Rimnel",
    "守護天使": "Guardian Angel",
    "エントランス": "entrance",
    "コッケン様": "Cuckoo",
    "コッケン祭り": "Cuckoo Festival",
    "スイッチ": "switch",
    "ターボアクセル": "Turbo Accel",
    "イタ映え":"pinteresting",
    "ダーマ神官": "Abbey Priest",
    "クエストスキップ": "Quest Skip",
    "魔族":"demon"
}
