---
on:
  push:
    branches:
      - "dev"
    paths:
      - "csv/glossary.csv"
      - "json/**"

jobs:
  run-checks:
    name: "Check if files are valid"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'
      - name: Run check script
        env:
          DEEPL_API_KEY: ${{ secrets.DEEPL_API_KEY }}
        run: |
          pip install -r .github/workflows/requirements.txt
          python .github/workflows/checks.py
